/**
 * Append-only MongoDB audit log for WebSocket training events.
 *
 * PIX-3935 — Every message (connect, disconnect, session_message,
 * coaching_note, join, leave, origin_rejection, rate_limit_exceeded)
 * is persisted and queryable by sessionId.
 */

import { type Db, type Collection } from 'mongodb'

import { createBuildSafeLogger } from '../../logging/build-safe-logger'

const logger = createBuildSafeLogger('training-audit-log')

export const AUDIT_LOG_COLLECTION = 'training_audit_log'

/** A single audit log entry. */
export interface AuditLogEntry {
  /** Unique entry ID (auto-generated by Mongo). */
  _id?: string
  /** Session this event belongs to. */
  sessionId: string
  /** User who triggered the event. */
  userId: string
  /** User's training role at time of event. */
  role: string
  /** Event type (connect, disconnect, session_message, coaching_note, etc.). */
  type: string
  /** ISO timestamp. */
  ts: string
  /** Optional structured payload. */
  payload?: Record<string, unknown>
}

export class AuditLog {
  private readonly collection: Collection<AuditLogEntry>

  constructor(db: Db) {
    this.collection = db.collection<AuditLogEntry>(AUDIT_LOG_COLLECTION)

    // Ensure indexes for common queries
    void this.collection.createIndexes([
      { key: { sessionId: 1, ts: -1 } },
      { key: { userId: 1, ts: -1 } },
      { key: { type: 1 } },
      { key: { ts: -1 } },
    ])
  }

  /**
   * Write a single audit entry.
   */
  async write(entry: Omit<AuditLogEntry, '_id'>): Promise<void> {
    try {
      await this.collection.insertOne({
        ...entry,
        ts: entry.ts ?? new Date().toISOString(),
      })
    } catch (err) {
      logger.error('Audit log write failed', {
        error: err instanceof Error ? err.message : String(err),
        sessionId: entry.sessionId,
        type: entry.type,
      })
    }
  }

  /**
   * Query audit entries by sessionId, most recent first.
   */
  async queryBySession(
    sessionId: string,
    limit = 100,
  ): Promise<AuditLogEntry[]> {
    return this.collection
      .find({ sessionId })
      .sort({ ts: -1 })
      .limit(limit)
      .toArray()
  }

  /**
   * Query audit entries by userId, most recent first.
   */
  async queryByUser(userId: string, limit = 100): Promise<AuditLogEntry[]> {
    return this.collection
      .find({ userId })
      .sort({ ts: -1 })
      .limit(limit)
      .toArray()
  }
}
