/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BiasAnalysisRequest,
  BiasAnalysisResult,
} from '../models/index';
import {
    BiasAnalysisRequestFromJSON,
    BiasAnalysisRequestToJSON,
    BiasAnalysisResultFromJSON,
    BiasAnalysisResultToJSON,
} from '../models/index';

export interface AnalyzeBiasRequest {
    biasAnalysisRequest: BiasAnalysisRequest;
}

/**
 * 
 */
export class BiasAnalysisApi extends runtime.BaseAPI {

    /**
     * Perform bias analysis on clinical text.
     * Analyze Bias
     */
    async analyzeBiasRaw(requestParameters: AnalyzeBiasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiasAnalysisResult>> {
        if (requestParameters['biasAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'biasAnalysisRequest',
                'Required parameter "biasAnalysisRequest" was null or undefined when calling analyzeBias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/bias-analysis/analyze`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BiasAnalysisRequestToJSON(requestParameters['biasAnalysisRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiasAnalysisResultFromJSON(jsonValue));
    }

    /**
     * Perform bias analysis on clinical text.
     * Analyze Bias
     */
    async analyzeBias(biasAnalysisRequest: BiasAnalysisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiasAnalysisResult> {
        const response = await this.analyzeBiasRaw({ biasAnalysisRequest: biasAnalysisRequest }, initOverrides);
        return await response.value();
    }

}
