/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  V1CreateMemoryRequest,
  V1CreateMemoryResponse,
  V1DeleteMemoryResponse,
  V1Error,
  V1GetMemoryResponse,
  V1ListMemoriesResponse,
  V1SearchMemoriesResponse,
  V1SearchMemoryRequest,
  V1UpdateMemoryRequest,
  V1UpdateMemoryResponse,
} from '../models/index';
import {
    V1CreateMemoryRequestFromJSON,
    V1CreateMemoryRequestToJSON,
    V1CreateMemoryResponseFromJSON,
    V1CreateMemoryResponseToJSON,
    V1DeleteMemoryResponseFromJSON,
    V1DeleteMemoryResponseToJSON,
    V1ErrorFromJSON,
    V1ErrorToJSON,
    V1GetMemoryResponseFromJSON,
    V1GetMemoryResponseToJSON,
    V1ListMemoriesResponseFromJSON,
    V1ListMemoriesResponseToJSON,
    V1SearchMemoriesResponseFromJSON,
    V1SearchMemoriesResponseToJSON,
    V1SearchMemoryRequestFromJSON,
    V1SearchMemoryRequestToJSON,
    V1UpdateMemoryRequestFromJSON,
    V1UpdateMemoryRequestToJSON,
    V1UpdateMemoryResponseFromJSON,
    V1UpdateMemoryResponseToJSON,
} from '../models/index';

export interface V1CreateMemoryOperationRequest {
    v1CreateMemoryRequest: V1CreateMemoryRequest;
}

export interface V1DeleteMemoryRequest {
    memoryId: string;
}

export interface V1GetMemoryRequest {
    memoryId: string;
}

export interface V1ListMemoriesRequest {
    limit?: number;
    offset?: number;
    category?: string;
    tags?: Array<string>;
}

export interface V1SearchMemoriesGetRequest {
    q: string;
    limit?: number;
    offset?: number;
}

export interface V1SearchMemoriesPostRequest {
    v1SearchMemoryRequest: V1SearchMemoryRequest;
}

export interface V1UpdateMemoryOperationRequest {
    memoryId: string;
    v1UpdateMemoryRequest: V1UpdateMemoryRequest;
}

/**
 * 
 */
export class MemoryV1Api extends runtime.BaseAPI {

    /**
     * Canonical v1 public memory API. Identity fields are derived from the caller\'s session and are rejected if supplied. Strict validation — unknown fields return 400. 
     * Create a memory (v1)
     */
    async v1CreateMemoryRaw(requestParameters: V1CreateMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1CreateMemoryResponse>> {
        if (requestParameters['v1CreateMemoryRequest'] == null) {
            throw new runtime.RequiredError(
                'v1CreateMemoryRequest',
                'Required parameter "v1CreateMemoryRequest" was null or undefined when calling v1CreateMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1CreateMemoryRequestToJSON(requestParameters['v1CreateMemoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1CreateMemoryResponseFromJSON(jsonValue));
    }

    /**
     * Canonical v1 public memory API. Identity fields are derived from the caller\'s session and are rejected if supplied. Strict validation — unknown fields return 400. 
     * Create a memory (v1)
     */
    async v1CreateMemory(v1CreateMemoryRequest: V1CreateMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1CreateMemoryResponse> {
        const response = await this.v1CreateMemoryRaw({ v1CreateMemoryRequest: v1CreateMemoryRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a memory (v1)
     */
    async v1DeleteMemoryRaw(requestParameters: V1DeleteMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1DeleteMemoryResponse>> {
        if (requestParameters['memoryId'] == null) {
            throw new runtime.RequiredError(
                'memoryId',
                'Required parameter "memoryId" was null or undefined when calling v1DeleteMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory/{memoryId}`.replace(`{${"memoryId"}}`, encodeURIComponent(String(requestParameters['memoryId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1DeleteMemoryResponseFromJSON(jsonValue));
    }

    /**
     * Delete a memory (v1)
     */
    async v1DeleteMemory(memoryId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1DeleteMemoryResponse> {
        const response = await this.v1DeleteMemoryRaw({ memoryId: memoryId }, initOverrides);
        return await response.value();
    }

    /**
     * Get a memory by id (v1)
     */
    async v1GetMemoryRaw(requestParameters: V1GetMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1GetMemoryResponse>> {
        if (requestParameters['memoryId'] == null) {
            throw new runtime.RequiredError(
                'memoryId',
                'Required parameter "memoryId" was null or undefined when calling v1GetMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory/{memoryId}`.replace(`{${"memoryId"}}`, encodeURIComponent(String(requestParameters['memoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1GetMemoryResponseFromJSON(jsonValue));
    }

    /**
     * Get a memory by id (v1)
     */
    async v1GetMemory(memoryId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1GetMemoryResponse> {
        const response = await this.v1GetMemoryRaw({ memoryId: memoryId }, initOverrides);
        return await response.value();
    }

    /**
     * Canonical v1 public memory API. Returns only the fields the public contract promises — see `docs/api/memory-v1-contract.md` and `src/lib/memory/contract/v1.ts`.  Identity (`userId`, `accountId`, `workspaceId`, `tenantId`) is resolved server-side from the caller\'s session; it is NEVER accepted as a query parameter. 
     * List memories (v1)
     */
    async v1ListMemoriesRaw(requestParameters: V1ListMemoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1ListMemoriesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1ListMemoriesResponseFromJSON(jsonValue));
    }

    /**
     * Canonical v1 public memory API. Returns only the fields the public contract promises — see `docs/api/memory-v1-contract.md` and `src/lib/memory/contract/v1.ts`.  Identity (`userId`, `accountId`, `workspaceId`, `tenantId`) is resolved server-side from the caller\'s session; it is NEVER accepted as a query parameter. 
     * List memories (v1)
     */
    async v1ListMemories(limit?: number, offset?: number, category?: string, tags?: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1ListMemoriesResponse> {
        const response = await this.v1ListMemoriesRaw({ limit: limit, offset: offset, category: category, tags: tags }, initOverrides);
        return await response.value();
    }

    /**
     * Search memories (v1, query string)
     */
    async v1SearchMemoriesGetRaw(requestParameters: V1SearchMemoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SearchMemoriesResponse>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling v1SearchMemoriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SearchMemoriesResponseFromJSON(jsonValue));
    }

    /**
     * Search memories (v1, query string)
     */
    async v1SearchMemoriesGet(q: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SearchMemoriesResponse> {
        const response = await this.v1SearchMemoriesGetRaw({ q: q, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Search memories (v1, JSON body)
     */
    async v1SearchMemoriesPostRaw(requestParameters: V1SearchMemoriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1SearchMemoriesResponse>> {
        if (requestParameters['v1SearchMemoryRequest'] == null) {
            throw new runtime.RequiredError(
                'v1SearchMemoryRequest',
                'Required parameter "v1SearchMemoryRequest" was null or undefined when calling v1SearchMemoriesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1SearchMemoryRequestToJSON(requestParameters['v1SearchMemoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1SearchMemoriesResponseFromJSON(jsonValue));
    }

    /**
     * Search memories (v1, JSON body)
     */
    async v1SearchMemoriesPost(v1SearchMemoryRequest: V1SearchMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1SearchMemoriesResponse> {
        const response = await this.v1SearchMemoriesPostRaw({ v1SearchMemoryRequest: v1SearchMemoryRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Full content replacement with optional metadata.
     * Update a memory (v1)
     */
    async v1UpdateMemoryRaw(requestParameters: V1UpdateMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1UpdateMemoryResponse>> {
        if (requestParameters['memoryId'] == null) {
            throw new runtime.RequiredError(
                'memoryId',
                'Required parameter "memoryId" was null or undefined when calling v1UpdateMemory().'
            );
        }

        if (requestParameters['v1UpdateMemoryRequest'] == null) {
            throw new runtime.RequiredError(
                'v1UpdateMemoryRequest',
                'Required parameter "v1UpdateMemoryRequest" was null or undefined when calling v1UpdateMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/memory/{memoryId}`.replace(`{${"memoryId"}}`, encodeURIComponent(String(requestParameters['memoryId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: V1UpdateMemoryRequestToJSON(requestParameters['v1UpdateMemoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1UpdateMemoryResponseFromJSON(jsonValue));
    }

    /**
     * Full content replacement with optional metadata.
     * Update a memory (v1)
     */
    async v1UpdateMemory(memoryId: string, v1UpdateMemoryRequest: V1UpdateMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1UpdateMemoryResponse> {
        const response = await this.v1UpdateMemoryRaw({ memoryId: memoryId, v1UpdateMemoryRequest: v1UpdateMemoryRequest }, initOverrides);
        return await response.value();
    }

}
