/**
 * PDF Exporter — renders compliance reports as PDF documents.
 *
 * Uses PDFKit to generate structured PDF reports with headers,
 * section titles, data tables, and summary blocks.
 */

import PDFDocument from 'pdfkit';
import type { ComplianceReport, ReportMetadata } from '../types';
import type {
  HIPAAAuditReport,
  SOC2SecurityReport,
  SOC2AvailabilityReport,
  ConsentComplianceReport,
  AccessReviewReport,
} from '../types';

// ---------------------------------------------------------------------------
// PDF helpers
// ---------------------------------------------------------------------------

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 612; // Letter
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

interface PDFRenderContext {
  doc: InstanceType<typeof PDFDocument>;
  y: number;
}

function ensureSpace(ctx: PDFRenderContext, needed: number): void {
  if (ctx.y + needed > 792 - PAGE_MARGIN) {
    ctx.doc.addPage();
    ctx.y = PAGE_MARGIN;
  }
}

function writeTitle(ctx: PDFRenderContext, text: string): void {
  ensureSpace(ctx, 40);
  ctx.doc.fontSize(18).font('Helvetica-Bold');
  ctx.doc.text(text, PAGE_MARGIN, ctx.y);
  ctx.y += 28;
}

function writeSection(ctx: PDFRenderContext, text: string): void {
  ensureSpace(ctx, 30);
  ctx.doc.fontSize(13).font('Helvetica-Bold');
  ctx.doc.text(text, PAGE_MARGIN, ctx.y);
  ctx.y += 22;
}

function writeLabel(ctx: PDFRenderContext, label: string, value: string): void {
  ensureSpace(ctx, 18);
  ctx.doc.fontSize(10).font('Helvetica-Bold');
  ctx.doc.text(`${label}: `, PAGE_MARGIN, ctx.y, { continued: true });
  ctx.doc.font('Helvetica').text(value);
  ctx.y += 16;
}

function writeKV(ctx: PDFRenderContext, label: string, value: string | number | boolean): void {
  writeLabel(ctx, label, String(value));
}

function writeTable(ctx: PDFRenderContext, headers: string[], rows: string[][]): void {
  const colWidth = CONTENT_WIDTH / headers.length;
  const rowHeight = 20;

  // Header row
  ensureSpace(ctx, rowHeight);
  ctx.doc.fontSize(9).font('Helvetica-Bold');
  headers.forEach((header, i) => {
    ctx.doc.text(header, PAGE_MARGIN + i * colWidth, ctx.y, { width: colWidth - 4 });
  });
  ctx.y += rowHeight;

  // Data rows
  ctx.doc.font('Helvetica');
  for (const row of rows) {
    ensureSpace(ctx, rowHeight);
    row.forEach((cell, i) => {
      ctx.doc.text(cell, PAGE_MARGIN + i * colWidth, ctx.y, { width: colWidth - 4 });
    });
    ctx.y += rowHeight;
  }
  ctx.y += 6;
}

function writeParagraph(ctx: PDFRenderContext, text: string): void {
  ensureSpace(ctx, 30);
  ctx.doc.fontSize(10).font('Helvetica');
  ctx.doc.text(text, PAGE_MARGIN, ctx.y, { width: CONTENT_WIDTH });
  ctx.y += ctx.doc.currentLineHeight() * 2 + 4;
}

// ---------------------------------------------------------------------------
// Report-specific renderers
// ---------------------------------------------------------------------------

function renderMetadata(ctx: PDFRenderContext, report: ComplianceReport, meta: ReportMetadata): void {
  writeSection(ctx, 'Report Information');
  writeKV(ctx, 'Report ID', report.reportId);
  writeKV(ctx, 'Type', report.reportType);
  writeKV(ctx, 'Generated At', report.generatedAt);
  writeKV(ctx, 'Period', `${report.period.startDate} to ${report.period.endDate}`);
  writeKV(ctx, 'Tenant ID', report.tenantId);
  writeKV(ctx, 'Generated By', meta.generatedBy);
  writeKV(ctx, 'Status', meta.status);
  ctx.y += 8;
}

function renderHIPAAAudit(ctx: PDFRenderContext, report: HIPAAAuditReport): void {
  writeSection(ctx, 'Audit Chain Verification');
  writeKV(ctx, 'Chain Valid', report.chainVerification.valid);
  writeKV(ctx, 'Total Events', report.chainVerification.totalEvents);
  if (report.chainVerification.brokenAtId) {
    writeKV(ctx, 'Broken At ID', report.chainVerification.brokenAtId);
    writeKV(ctx, 'Reason', report.chainVerification.reason ?? 'Unknown');
  }
  ctx.y += 8;

  writeSection(ctx, 'PHI Access Events');
  writeKV(ctx, 'Total PHI Access', report.summary.totalPhiAccess);
  writeKV(ctx, 'Failed Access', report.summary.failedAccess);
  writeKV(ctx, 'Unique Users', report.summary.uniqueUsers);
  writeKV(ctx, 'Unique Patients', report.summary.uniquePatients);
  if (report.phiAccessEvents.length > 0) {
    const rows = report.phiAccessEvents.slice(0, 50).map((e) => [
      e.timestamp.slice(0, 19),
      e.userId,
      e.action,
      e.resourceType,
      e.status,
    ]);
    writeTable(ctx, ['Timestamp', 'User', 'Action', 'Resource', 'Status'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'PHI Modification Events');
  writeKV(ctx, 'Total Modifications', report.summary.totalPhiModifications);
  if (report.phiModificationEvents.length > 0) {
    const rows = report.phiModificationEvents.slice(0, 50).map((e) => [
      e.timestamp.slice(0, 19),
      e.userId,
      e.action,
      e.resourceType,
      e.status,
    ]);
    writeTable(ctx, ['Timestamp', 'User', 'Action', 'Resource', 'Status'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Break-Glass Events');
  writeKV(ctx, 'Total Break-Glass', report.summary.totalBreakGlass);
  if (report.breakGlassEvents.length > 0) {
    const rows = report.breakGlassEvents.slice(0, 50).map((e) => [
      e.timestamp.slice(0, 19),
      e.userId,
      e.reason,
      e.resourceType,
    ]);
    writeTable(ctx, ['Timestamp', 'User', 'Reason', 'Resource'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Summary');
  writeKV(ctx, 'Chain Valid', report.summary.chainValid);
}

function renderSOC2Security(ctx: PDFRenderContext, report: SOC2SecurityReport): void {
  writeSection(ctx, 'Access Controls');
  writeKV(ctx, 'Total Users', report.accessControls.totalUsers);
  writeKV(ctx, 'Permission Grants', report.accessControls.permissionGrants);
  writeKV(ctx, 'Permission Revocations', report.accessControls.permissionRevocations);
  writeKV(ctx, 'MFA Required Permissions', report.accessControls.mfaRequiredPermissions);
  if (report.accessControls.roleAssignments.length > 0) {
    const rows = report.accessControls.roleAssignments.map((r) => [
      r.role,
      String(r.count),
      r.permissions.join(', '),
    ]);
    writeTable(ctx, ['Role', 'Count', 'Permissions'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Audit Log Integrity');
  writeKV(ctx, 'Chain Valid', report.auditLogIntegrity.valid);
  writeKV(ctx, 'Total Events', report.auditLogIntegrity.totalEvents);
  ctx.y += 8;

  writeSection(ctx, 'Encryption');
  writeKV(ctx, 'Data in Transit', report.encryption.dataInTransit);
  writeKV(ctx, 'Data at Rest', report.encryption.dataAtRest);
  writeKV(ctx, 'Audit Log Hashing', report.encryption.auditLogHashing);
  writeKV(ctx, 'Algorithm', report.encryption.algorithm);
  ctx.y += 8;

  writeSection(ctx, 'Security Incidents');
  writeKV(ctx, 'Total Incidents', report.incidents.length);
  writeKV(ctx, 'Open Incidents', report.summary.openIncidents);
  if (report.incidents.length > 0) {
    const rows = report.incidents.slice(0, 50).map((i) => [
      i.timestamp.slice(0, 19),
      i.severity,
      i.type,
      i.resolved ? 'Resolved' : 'Open',
    ]);
    writeTable(ctx, ['Timestamp', 'Severity', 'Type', 'Status'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Summary');
  writeKV(ctx, 'Encryption Compliant', report.summary.encryptionCompliant);
  writeKV(ctx, 'Chain Valid', report.summary.chainValid);
}

function renderSOC2Availability(ctx: PDFRenderContext, report: SOC2AvailabilityReport): void {
  writeSection(ctx, 'Uptime');
  writeKV(ctx, 'Uptime Percentage', `${report.uptime.totalUptimePercentage}%`);
  writeKV(ctx, 'Total Downtime (minutes)', report.uptime.totalDowntimeMinutes);
  if (report.uptime.incidents.length > 0) {
    const rows = report.uptime.incidents.map((i) => [
      i.startTime.slice(0, 19),
      String(i.durationMinutes),
      i.description,
    ]);
    writeTable(ctx, ['Start Time', 'Duration (min)', 'Description'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Backup & Restore');
  writeKV(ctx, 'Last Backup', report.backupRestore.lastBackupAt);
  writeKV(ctx, 'Backup Frequency', report.backupRestore.backupFrequency);
  writeKV(ctx, 'Backup Encryption', report.backupRestore.backupEncryption);
  if (report.backupRestore.lastRestoreTest) {
    writeKV(ctx, 'Last Restore Test', report.backupRestore.lastRestoreTest);
  }
  ctx.y += 8;

  writeSection(ctx, 'Disaster Recovery');
  writeKV(ctx, 'DR Plan Version', report.disasterRecovery.drPlanVersion);
  if (report.disasterRecovery.lastTestDate) {
    writeKV(ctx, 'Last Test Date', report.disasterRecovery.lastTestDate);
  }
  writeKV(ctx, 'RTO (minutes)', report.disasterRecovery.rtoMinutes);
  writeKV(ctx, 'RPO (minutes)', report.disasterRecovery.rpoMinutes);
  ctx.y += 8;

  writeSection(ctx, 'Summary');
  writeKV(ctx, 'Backup Compliant', report.summary.backupCompliant);
  writeKV(ctx, 'DR Compliant', report.summary.drCompliant);
}

function renderConsentCompliance(ctx: PDFRenderContext, report: ConsentComplianceReport): void {
  writeSection(ctx, 'By State');
  if (report.byState.length > 0) {
    const rows = report.byState.map((s) => [
      s.stateCode,
      String(s.totalConsents),
      String(s.activeConsents),
      String(s.expiredConsents),
      String(s.revokedConsents),
      `${s.complianceRate}%`,
    ]);
    writeTable(ctx, ['State', 'Total', 'Active', 'Expired', 'Revoked', 'Compliance'], rows);
  } else {
    writeParagraph(ctx, 'No consent records found for this period.');
  }
  ctx.y += 8;

  writeSection(ctx, 'By Treatment Category');
  if (report.byTreatment.length > 0) {
    const rows = report.byTreatment.map((t) => [
      t.treatmentCategory,
      String(t.totalConsents),
      String(t.activeConsents),
      String(t.expiredConsents),
      `${t.complianceRate}%`,
    ]);
    writeTable(ctx, ['Category', 'Total', 'Active', 'Expired', 'Compliance'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Expiring Consents (30 days)');
  writeKV(ctx, 'Expiring Within 30 Days', report.summary.expiringWithin30Days);
  if (report.expiringConsents.length > 0) {
    const rows = report.expiringConsents.slice(0, 50).map((e) => [
      e.consentId,
      e.patientId,
      e.stateCode,
      e.category,
      String(e.daysUntilExpiry),
    ]);
    writeTable(ctx, ['Consent ID', 'Patient', 'State', 'Category', 'Days Left'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Summary');
  writeKV(ctx, 'Overall Compliance Rate', `${report.summary.overallComplianceRate}%`);
  writeKV(ctx, 'States Covered', report.summary.statesCovered);
}

function renderAccessReview(ctx: PDFRenderContext, report: AccessReviewReport): void {
  writeSection(ctx, 'Role Assignments');
  writeKV(ctx, 'Total Active Assignments', report.summary.totalActiveAssignments);
  writeKV(ctx, 'Total Users', report.summary.totalUsers);
  writeKV(ctx, 'Total Roles', report.summary.totalRoles);
  if (report.roleAssignments.length > 0) {
    const rows = report.roleAssignments.slice(0, 50).map((a) => [
      a.userId,
      a.role,
      String(a.permissions.length),
      a.active ? 'Active' : 'Inactive',
    ]);
    writeTable(ctx, ['User ID', 'Role', 'Permissions', 'Status'], rows);
  }
  ctx.y += 8;

  writeSection(ctx, 'Permission Changes');
  writeKV(ctx, 'Grants', report.summary.grants);
  writeKV(ctx, 'Revocations', report.summary.revocations);
  writeKV(ctx, 'High-Risk Permissions', report.summary.highRiskPermissions);
  if (report.permissionChanges.length > 0) {
    const rows = report.permissionChanges.slice(0, 50).map((c) => [
      c.timestamp.slice(0, 19),
      c.userId,
      c.type,
      c.permission,
      c.role,
    ]);
    writeTable(ctx, ['Timestamp', 'User', 'Type', 'Permission', 'Role'], rows);
  }
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Export a compliance report as a PDF document.
 * Returns a Buffer containing the PDF file.
 */
export async function exportReportToPDF(
  report: ComplianceReport,
  metadata: ReportMetadata,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'LETTER' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const ctx: PDFRenderContext = { doc, y: PAGE_MARGIN };

    // Title
    const titleMap: Record<string, string> = {
      hipaa_audit: 'HIPAA Audit Report',
      soc2_security: 'SOC 2 Security Report',
      soc2_availability: 'SOC 2 Availability Report',
      consent_compliance: 'Consent Compliance Report',
      access_review: 'Access Review Report',
    };

    writeTitle(ctx, titleMap[report.reportType] ?? 'Compliance Report');

    // Metadata section
    renderMetadata(ctx, report, metadata);

    // Report-specific content
    switch (report.reportType) {
      case 'hipaa_audit':
        renderHIPAAAudit(ctx, report);
        break;
      case 'soc2_security':
        renderSOC2Security(ctx, report);
        break;
      case 'soc2_availability':
        renderSOC2Availability(ctx, report);
        break;
      case 'consent_compliance':
        renderConsentCompliance(ctx, report);
        break;
      case 'access_review':
        renderAccessReview(ctx, report);
        break;
      default: {
        const exhaustive: never = report;
        throw new Error(`Unsupported report type for PDF: ${JSON.stringify(exhaustive)}`);
      }
    }

    // Footer
    ensureSpace(ctx, 30);
    ctx.y += 20;
    ctx.doc.fontSize(8).font('Helvetica-Oblique');
    ctx.doc.text(
      `Generated by Pixelated Empathy Compliance Reporting | ${new Date().toISOString()}`,
      PAGE_MARGIN,
      ctx.y,
      { width: CONTENT_WIDTH, align: 'center' },
    );

    doc.end();
  });
}
