/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCallback200Response
 */
export interface AuthCallback200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthCallback200Response
     */
    success?: boolean;
    /**
     * Internal platform UUID
     * @type {string}
     * @memberof AuthCallback200Response
     */
    userId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthCallback200Response
     */
    isNewUser?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthCallback200Response
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthCallback200Response
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthCallback200Response
     */
    tokenType?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthCallback200Response
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the AuthCallback200Response interface.
 */
export function instanceOfAuthCallback200Response(value: object): value is AuthCallback200Response {
    return true;
}

export function AuthCallback200ResponseFromJSON(json: any): AuthCallback200Response {
    return AuthCallback200ResponseFromJSONTyped(json, false);
}

export function AuthCallback200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCallback200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'isNewUser': json['isNewUser'] == null ? undefined : json['isNewUser'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
    };
}

export function AuthCallback200ResponseToJSON(json: any): AuthCallback200Response {
    return AuthCallback200ResponseToJSONTyped(json, false);
}

export function AuthCallback200ResponseToJSONTyped(value?: AuthCallback200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'userId': value['userId'],
        'isNewUser': value['isNewUser'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'tokenType': value['tokenType'],
        'expiresIn': value['expiresIn'],
    };
}

