/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiasAnalysisResultBiasesInner } from './BiasAnalysisResultBiasesInner';
import {
    BiasAnalysisResultBiasesInnerFromJSON,
    BiasAnalysisResultBiasesInnerFromJSONTyped,
    BiasAnalysisResultBiasesInnerToJSON,
    BiasAnalysisResultBiasesInnerToJSONTyped,
} from './BiasAnalysisResultBiasesInner';

/**
 * 
 * @export
 * @interface BiasAnalysisResult
 */
export interface BiasAnalysisResult {
    /**
     * 
     * @type {string}
     * @memberof BiasAnalysisResult
     */
    id?: string;
    /**
     * 
     * @type {Array<BiasAnalysisResultBiasesInner>}
     * @memberof BiasAnalysisResult
     */
    biases?: Array<BiasAnalysisResultBiasesInner>;
    /**
     * 
     * @type {number}
     * @memberof BiasAnalysisResult
     */
    overallScore?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof BiasAnalysisResult
     */
    recommendations?: Array<string>;
}

/**
 * Check if a given object implements the BiasAnalysisResult interface.
 */
export function instanceOfBiasAnalysisResult(value: object): value is BiasAnalysisResult {
    return true;
}

export function BiasAnalysisResultFromJSON(json: any): BiasAnalysisResult {
    return BiasAnalysisResultFromJSONTyped(json, false);
}

export function BiasAnalysisResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiasAnalysisResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'biases': json['biases'] == null ? undefined : ((json['biases'] as Array<any>).map(BiasAnalysisResultBiasesInnerFromJSON)),
        'overallScore': json['overallScore'] == null ? undefined : json['overallScore'],
        'recommendations': json['recommendations'] == null ? undefined : json['recommendations'],
    };
}

export function BiasAnalysisResultToJSON(json: any): BiasAnalysisResult {
    return BiasAnalysisResultToJSONTyped(json, false);
}

export function BiasAnalysisResultToJSONTyped(value?: BiasAnalysisResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'biases': value['biases'] == null ? undefined : ((value['biases'] as Array<any>).map(BiasAnalysisResultBiasesInnerToJSON)),
        'overallScore': value['overallScore'],
        'recommendations': value['recommendations'],
    };
}

