/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientProfile
 */
export interface ClientProfile {
    /**
     * 
     * @type {string}
     * @memberof ClientProfile
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ClientProfile
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientProfile
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientProfile
     */
    personalityType?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientProfile
     */
    presentingProblem: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClientProfile
     */
    triggers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClientProfile
     */
    strengths?: Array<string>;
}

/**
 * Check if a given object implements the ClientProfile interface.
 */
export function instanceOfClientProfile(value: object): value is ClientProfile {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('presentingProblem' in value) || value['presentingProblem'] === undefined) return false;
    return true;
}

export function ClientProfileFromJSON(json: any): ClientProfile {
    return ClientProfileFromJSONTyped(json, false);
}

export function ClientProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'age': json['age'] == null ? undefined : json['age'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'personalityType': json['personalityType'] == null ? undefined : json['personalityType'],
        'presentingProblem': json['presentingProblem'],
        'triggers': json['triggers'] == null ? undefined : json['triggers'],
        'strengths': json['strengths'] == null ? undefined : json['strengths'],
    };
}

export function ClientProfileToJSON(json: any): ClientProfile {
    return ClientProfileToJSONTyped(json, false);
}

export function ClientProfileToJSONTyped(value?: ClientProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'age': value['age'],
        'gender': value['gender'],
        'personalityType': value['personalityType'],
        'presentingProblem': value['presentingProblem'],
        'triggers': value['triggers'],
        'strengths': value['strengths'],
    };
}

