/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientProfile } from './ClientProfile';
import {
    ClientProfileFromJSON,
    ClientProfileFromJSONTyped,
    ClientProfileToJSON,
    ClientProfileToJSONTyped,
} from './ClientProfile';

/**
 * 
 * @export
 * @interface CreateTrainingSessionRequest
 */
export interface CreateTrainingSessionRequest {
    /**
     * 
     * @type {ClientProfile}
     * @memberof CreateTrainingSessionRequest
     */
    clientProfile: ClientProfile;
    /**
     * 
     * @type {number}
     * @memberof CreateTrainingSessionRequest
     */
    difficultyLevel?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    traineeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingSessionRequest
     */
    supervisorId?: string;
}

/**
 * Check if a given object implements the CreateTrainingSessionRequest interface.
 */
export function instanceOfCreateTrainingSessionRequest(value: object): value is CreateTrainingSessionRequest {
    if (!('clientProfile' in value) || value['clientProfile'] === undefined) return false;
    return true;
}

export function CreateTrainingSessionRequestFromJSON(json: any): CreateTrainingSessionRequest {
    return CreateTrainingSessionRequestFromJSONTyped(json, false);
}

export function CreateTrainingSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientProfile': ClientProfileFromJSON(json['clientProfile']),
        'difficultyLevel': json['difficultyLevel'] == null ? undefined : json['difficultyLevel'],
        'traineeId': json['traineeId'] == null ? undefined : json['traineeId'],
        'supervisorId': json['supervisorId'] == null ? undefined : json['supervisorId'],
    };
}

export function CreateTrainingSessionRequestToJSON(json: any): CreateTrainingSessionRequest {
    return CreateTrainingSessionRequestToJSONTyped(json, false);
}

export function CreateTrainingSessionRequestToJSONTyped(value?: CreateTrainingSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientProfile': ClientProfileToJSON(value['clientProfile']),
        'difficultyLevel': value['difficultyLevel'],
        'traineeId': value['traineeId'],
        'supervisorId': value['supervisorId'],
    };
}

