/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Memory API (v1)
 * Public v1 memory API contract. Schemas derive from `src/lib/memory/contract/v1.ts`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorEnvelope
 */
export interface ErrorEnvelope {
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelope
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelope
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelope
     */
    code?: string;
}

/**
 * Check if a given object implements the ErrorEnvelope interface.
 */
export function instanceOfErrorEnvelope(value: object): value is ErrorEnvelope {
    return true;
}

export function ErrorEnvelopeFromJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeFromJSONTyped(json, false);
}

export function ErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ErrorEnvelopeToJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeToJSONTyped(json, false);
}

export function ErrorEnvelopeToJSONTyped(value?: ErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
        'code': value['code'],
    };
}

