/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FineTuningJob
 */
export interface FineTuningJob {
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    backend?: FineTuningJobBackendEnum;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    status?: FineTuningJobStatusEnum;
    /**
     * Training progress percentage (0-100)
     * @type {number}
     * @memberof FineTuningJob
     */
    progress?: number;
    /**
     * 
     * @type {number}
     * @memberof FineTuningJob
     */
    nEpochs?: number;
    /**
     * 
     * @type {number}
     * @memberof FineTuningJob
     */
    batchSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FineTuningJob
     */
    learningRateMultiplier?: number;
    /**
     * 
     * @type {string}
     * @memberof FineTuningJob
     */
    suffix?: string;
    /**
     * 
     * @type {Date}
     * @memberof FineTuningJob
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FineTuningJob
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const FineTuningJobBackendEnum = {
    Openai: 'openai',
    Huggingface: 'huggingface',
    Local: 'local',
    DryRun: 'dry-run'
} as const;
export type FineTuningJobBackendEnum = typeof FineTuningJobBackendEnum[keyof typeof FineTuningJobBackendEnum];

/**
 * @export
 */
export const FineTuningJobStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type FineTuningJobStatusEnum = typeof FineTuningJobStatusEnum[keyof typeof FineTuningJobStatusEnum];


/**
 * Check if a given object implements the FineTuningJob interface.
 */
export function instanceOfFineTuningJob(value: object): value is FineTuningJob {
    return true;
}

export function FineTuningJobFromJSON(json: any): FineTuningJob {
    return FineTuningJobFromJSONTyped(json, false);
}

export function FineTuningJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): FineTuningJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'model': json['model'] == null ? undefined : json['model'],
        'backend': json['backend'] == null ? undefined : json['backend'],
        'status': json['status'] == null ? undefined : json['status'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'nEpochs': json['nEpochs'] == null ? undefined : json['nEpochs'],
        'batchSize': json['batchSize'] == null ? undefined : json['batchSize'],
        'learningRateMultiplier': json['learningRateMultiplier'] == null ? undefined : json['learningRateMultiplier'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function FineTuningJobToJSON(json: any): FineTuningJob {
    return FineTuningJobToJSONTyped(json, false);
}

export function FineTuningJobToJSONTyped(value?: FineTuningJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'model': value['model'],
        'backend': value['backend'],
        'status': value['status'],
        'progress': value['progress'],
        'nEpochs': value['nEpochs'],
        'batchSize': value['batchSize'],
        'learningRateMultiplier': value['learningRateMultiplier'],
        'suffix': value['suffix'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

