/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMemoryStats200ResponseStats } from './GetMemoryStats200ResponseStats';
import {
    GetMemoryStats200ResponseStatsFromJSON,
    GetMemoryStats200ResponseStatsFromJSONTyped,
    GetMemoryStats200ResponseStatsToJSON,
    GetMemoryStats200ResponseStatsToJSONTyped,
} from './GetMemoryStats200ResponseStats';

/**
 * 
 * @export
 * @interface GetMemoryStats200Response
 */
export interface GetMemoryStats200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetMemoryStats200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetMemoryStats200ResponseStats}
     * @memberof GetMemoryStats200Response
     */
    stats?: GetMemoryStats200ResponseStats;
}

/**
 * Check if a given object implements the GetMemoryStats200Response interface.
 */
export function instanceOfGetMemoryStats200Response(value: object): value is GetMemoryStats200Response {
    return true;
}

export function GetMemoryStats200ResponseFromJSON(json: any): GetMemoryStats200Response {
    return GetMemoryStats200ResponseFromJSONTyped(json, false);
}

export function GetMemoryStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMemoryStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : GetMemoryStats200ResponseStatsFromJSON(json['stats']),
    };
}

export function GetMemoryStats200ResponseToJSON(json: any): GetMemoryStats200Response {
    return GetMemoryStats200ResponseToJSONTyped(json, false);
}

export function GetMemoryStats200ResponseToJSONTyped(value?: GetMemoryStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': GetMemoryStats200ResponseStatsToJSON(value['stats']),
    };
}

