/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKey } from './ApiKey';
import {
    ApiKeyFromJSON,
    ApiKeyFromJSONTyped,
    ApiKeyToJSON,
    ApiKeyToJSONTyped,
} from './ApiKey';

/**
 * 
 * @export
 * @interface ListApiKeys200Response
 */
export interface ListApiKeys200Response {
    /**
     * 
     * @type {Array<ApiKey>}
     * @memberof ListApiKeys200Response
     */
    keys?: Array<ApiKey>;
}

/**
 * Check if a given object implements the ListApiKeys200Response interface.
 */
export function instanceOfListApiKeys200Response(value: object): value is ListApiKeys200Response {
    return true;
}

export function ListApiKeys200ResponseFromJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseFromJSONTyped(json, false);
}

export function ListApiKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeys200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': json['keys'] == null ? undefined : ((json['keys'] as Array<any>).map(ApiKeyFromJSON)),
    };
}

export function ListApiKeys200ResponseToJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseToJSONTyped(json, false);
}

export function ListApiKeys200ResponseToJSONTyped(value?: ListApiKeys200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keys': value['keys'] == null ? undefined : ((value['keys'] as Array<any>).map(ApiKeyToJSON)),
    };
}

