/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingSession } from './TrainingSession';
import {
    TrainingSessionFromJSON,
    TrainingSessionFromJSONTyped,
    TrainingSessionToJSON,
    TrainingSessionToJSONTyped,
} from './TrainingSession';

/**
 * 
 * @export
 * @interface ListTrainingSessions200Response
 */
export interface ListTrainingSessions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListTrainingSessions200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<TrainingSession>}
     * @memberof ListTrainingSessions200Response
     */
    sessions?: Array<TrainingSession>;
}

/**
 * Check if a given object implements the ListTrainingSessions200Response interface.
 */
export function instanceOfListTrainingSessions200Response(value: object): value is ListTrainingSessions200Response {
    return true;
}

export function ListTrainingSessions200ResponseFromJSON(json: any): ListTrainingSessions200Response {
    return ListTrainingSessions200ResponseFromJSONTyped(json, false);
}

export function ListTrainingSessions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTrainingSessions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(TrainingSessionFromJSON)),
    };
}

export function ListTrainingSessions200ResponseToJSON(json: any): ListTrainingSessions200Response {
    return ListTrainingSessions200ResponseToJSONTyped(json, false);
}

export function ListTrainingSessions200ResponseToJSONTyped(value?: ListTrainingSessions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(TrainingSessionToJSON)),
    };
}

