/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { AdminUserView } from './AdminUserView';
import {
    AdminUserViewFromJSON,
    AdminUserViewFromJSONTyped,
    AdminUserViewToJSON,
    AdminUserViewToJSONTyped,
} from './AdminUserView';

/**
 * 
 * @export
 * @interface ListUsers200Response
 */
export interface ListUsers200Response {
    /**
     * 
     * @type {Array<AdminUserView>}
     * @memberof ListUsers200Response
     */
    data?: Array<AdminUserView>;
    /**
     * 
     * @type {Pagination}
     * @memberof ListUsers200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ListUsers200Response interface.
 */
export function instanceOfListUsers200Response(value: object): value is ListUsers200Response {
    return true;
}

export function ListUsers200ResponseFromJSON(json: any): ListUsers200Response {
    return ListUsers200ResponseFromJSONTyped(json, false);
}

export function ListUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AdminUserViewFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ListUsers200ResponseToJSON(json: any): ListUsers200Response {
    return ListUsers200ResponseToJSONTyped(json, false);
}

export function ListUsers200ResponseToJSONTyped(value?: ListUsers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AdminUserViewToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

