/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryTurn
 */
export interface MemoryTurn {
    /**
     * 
     * @type {string}
     * @memberof MemoryTurn
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryTurn
     */
    role?: MemoryTurnRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof MemoryTurn
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof MemoryTurn
     */
    timestamp?: Date;
    /**
     * 
     * @type {object}
     * @memberof MemoryTurn
     */
    metadata?: object;
}


/**
 * @export
 */
export const MemoryTurnRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system'
} as const;
export type MemoryTurnRoleEnum = typeof MemoryTurnRoleEnum[keyof typeof MemoryTurnRoleEnum];


/**
 * Check if a given object implements the MemoryTurn interface.
 */
export function instanceOfMemoryTurn(value: object): value is MemoryTurn {
    return true;
}

export function MemoryTurnFromJSON(json: any): MemoryTurn {
    return MemoryTurnFromJSONTyped(json, false);
}

export function MemoryTurnFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryTurn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function MemoryTurnToJSON(json: any): MemoryTurn {
    return MemoryTurnToJSONTyped(json, false);
}

export function MemoryTurnToJSONTyped(value?: MemoryTurn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'metadata': value['metadata'],
    };
}

