/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductMemoryRecord
 */
export interface ProductMemoryRecord {
    /**
     * 
     * @type {string}
     * @memberof ProductMemoryRecord
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductMemoryRecord
     */
    content?: string;
    /**
     * 
     * @type {object}
     * @memberof ProductMemoryRecord
     */
    metadata?: object;
    /**
     * 
     * @type {Date}
     * @memberof ProductMemoryRecord
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductMemoryRecord
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ProductMemoryRecord interface.
 */
export function instanceOfProductMemoryRecord(value: object): value is ProductMemoryRecord {
    return true;
}

export function ProductMemoryRecordFromJSON(json: any): ProductMemoryRecord {
    return ProductMemoryRecordFromJSONTyped(json, false);
}

export function ProductMemoryRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMemoryRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ProductMemoryRecordToJSON(json: any): ProductMemoryRecord {
    return ProductMemoryRecordToJSONTyped(json, false);
}

export function ProductMemoryRecordToJSONTyped(value?: ProductMemoryRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

