/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Memory API (v1)
 * Public v1 memory API contract. Schemas derive from `src/lib/memory/contract/v1.ts`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicMemory
 */
export interface PublicMemory {
    /**
     * 
     * @type {string}
     * @memberof PublicMemory
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicMemory
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicMemory
     */
    scope?: PublicMemoryScopeEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicMemory
     */
    retention?: PublicMemoryRetentionEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicMemory
     */
    category?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicMemory
     */
    tags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PublicMemory
     */
    version?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicMemory
     */
    importance?: number;
    /**
     * 
     * @type {Date}
     * @memberof PublicMemory
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PublicMemory
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const PublicMemoryScopeEnum = {
    Session: 'session',
    Arc: 'arc',
    Trait: 'trait',
    Fact: 'fact'
} as const;
export type PublicMemoryScopeEnum = typeof PublicMemoryScopeEnum[keyof typeof PublicMemoryScopeEnum];

/**
 * @export
 */
export const PublicMemoryRetentionEnum = {
    Ephemeral: 'ephemeral',
    ShortTerm: 'short_term',
    LongTerm: 'long_term',
    Permanent: 'permanent'
} as const;
export type PublicMemoryRetentionEnum = typeof PublicMemoryRetentionEnum[keyof typeof PublicMemoryRetentionEnum];


/**
 * Check if a given object implements the PublicMemory interface.
 */
export function instanceOfPublicMemory(value: object): value is PublicMemory {
    return true;
}

export function PublicMemoryFromJSON(json: any): PublicMemory {
    return PublicMemoryFromJSONTyped(json, false);
}

export function PublicMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicMemory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'retention': json['retention'] == null ? undefined : json['retention'],
        'category': json['category'] == null ? undefined : json['category'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'version': json['version'] == null ? undefined : json['version'],
        'importance': json['importance'] == null ? undefined : json['importance'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PublicMemoryToJSON(json: any): PublicMemory {
    return PublicMemoryToJSONTyped(json, false);
}

export function PublicMemoryToJSONTyped(value?: PublicMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'scope': value['scope'],
        'retention': value['retention'],
        'category': value['category'],
        'tags': value['tags'],
        'version': value['version'],
        'importance': value['importance'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

