/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RotateApiKey200ResponseKey
 */
export interface RotateApiKey200ResponseKey {
    /**
     * 
     * @type {string}
     * @memberof RotateApiKey200ResponseKey
     */
    id?: string;
    /**
     * New key value — shown only once
     * @type {string}
     * @memberof RotateApiKey200ResponseKey
     */
    plainKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RotateApiKey200ResponseKey
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof RotateApiKey200ResponseKey
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RotateApiKey200ResponseKey
     */
    expires?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof RotateApiKey200ResponseKey
     */
    scopes?: Array<string>;
}

/**
 * Check if a given object implements the RotateApiKey200ResponseKey interface.
 */
export function instanceOfRotateApiKey200ResponseKey(value: object): value is RotateApiKey200ResponseKey {
    return true;
}

export function RotateApiKey200ResponseKeyFromJSON(json: any): RotateApiKey200ResponseKey {
    return RotateApiKey200ResponseKeyFromJSONTyped(json, false);
}

export function RotateApiKey200ResponseKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateApiKey200ResponseKey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'plainKey': json['plain_key'] == null ? undefined : json['plain_key'],
        'name': json['name'] == null ? undefined : json['name'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}

export function RotateApiKey200ResponseKeyToJSON(json: any): RotateApiKey200ResponseKey {
    return RotateApiKey200ResponseKeyToJSONTyped(json, false);
}

export function RotateApiKey200ResponseKeyToJSONTyped(value?: RotateApiKey200ResponseKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'plain_key': value['plainKey'],
        'name': value['name'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'expires': value['expires'] == null ? undefined : ((value['expires']).toISOString()),
        'scopes': value['scopes'],
    };
}

