/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchMemoriesGet200ResponsePagination
 */
export interface SearchMemoriesGet200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof SearchMemoriesGet200ResponsePagination
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchMemoriesGet200ResponsePagination
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchMemoriesGet200ResponsePagination
     */
    total?: number;
}

/**
 * Check if a given object implements the SearchMemoriesGet200ResponsePagination interface.
 */
export function instanceOfSearchMemoriesGet200ResponsePagination(value: object): value is SearchMemoriesGet200ResponsePagination {
    return true;
}

export function SearchMemoriesGet200ResponsePaginationFromJSON(json: any): SearchMemoriesGet200ResponsePagination {
    return SearchMemoriesGet200ResponsePaginationFromJSONTyped(json, false);
}

export function SearchMemoriesGet200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMemoriesGet200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SearchMemoriesGet200ResponsePaginationToJSON(json: any): SearchMemoriesGet200ResponsePagination {
    return SearchMemoriesGet200ResponsePaginationToJSONTyped(json, false);
}

export function SearchMemoriesGet200ResponsePaginationToJSONTyped(value?: SearchMemoriesGet200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

