/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Memory API (v1)
 * Public v1 memory API contract. Schemas derive from `src/lib/memory/contract/v1.ts`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { PublicMemory } from './PublicMemory';
import {
    PublicMemoryFromJSON,
    PublicMemoryFromJSONTyped,
    PublicMemoryToJSON,
    PublicMemoryToJSONTyped,
} from './PublicMemory';

/**
 * 
 * @export
 * @interface SearchMemoriesResponse
 */
export interface SearchMemoriesResponse {
    /**
     * 
     * @type {Array<PublicMemory>}
     * @memberof SearchMemoriesResponse
     */
    data: Array<PublicMemory>;
    /**
     * Echo of the submitted search string
     * @type {string}
     * @memberof SearchMemoriesResponse
     */
    query: string;
    /**
     * 
     * @type {Pagination}
     * @memberof SearchMemoriesResponse
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the SearchMemoriesResponse interface.
 */
export function instanceOfSearchMemoriesResponse(value: object): value is SearchMemoriesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function SearchMemoriesResponseFromJSON(json: any): SearchMemoriesResponse {
    return SearchMemoriesResponseFromJSONTyped(json, false);
}

export function SearchMemoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMemoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PublicMemoryFromJSON)),
        'query': json['query'],
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function SearchMemoriesResponseToJSON(json: any): SearchMemoriesResponse {
    return SearchMemoriesResponseToJSONTyped(json, false);
}

export function SearchMemoriesResponseToJSONTyped(value?: SearchMemoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PublicMemoryToJSON)),
        'query': value['query'],
        'pagination': PaginationToJSON(value['pagination']),
    };
}

