/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Memory API (v1)
 * Public v1 memory API contract. Schemas derive from `src/lib/memory/contract/v1.ts`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchMemoryRequest
 */
export interface SearchMemoryRequest {
    /**
     * Search query string
     * @type {string}
     * @memberof SearchMemoryRequest
     */
    q: string;
    /**
     * 
     * @type {number}
     * @memberof SearchMemoryRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchMemoryRequest
     */
    offset?: number;
}

/**
 * Check if a given object implements the SearchMemoryRequest interface.
 */
export function instanceOfSearchMemoryRequest(value: object): value is SearchMemoryRequest {
    if (!('q' in value) || value['q'] === undefined) return false;
    return true;
}

export function SearchMemoryRequestFromJSON(json: any): SearchMemoryRequest {
    return SearchMemoryRequestFromJSONTyped(json, false);
}

export function SearchMemoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMemoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'q': json['q'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function SearchMemoryRequestToJSON(json: any): SearchMemoryRequest {
    return SearchMemoryRequestToJSONTyped(json, false);
}

export function SearchMemoryRequestToJSONTyped(value?: SearchMemoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'q': value['q'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

