/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitTrainingJobRequest
 */
export interface SubmitTrainingJobRequest {
    /**
     * Base model to fine-tune
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    backend: SubmitTrainingJobRequestBackendEnum;
    /**
     * 
     * @type {number}
     * @memberof SubmitTrainingJobRequest
     */
    nEpochs?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmitTrainingJobRequest
     */
    batchSize?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmitTrainingJobRequest
     */
    learningRateMultiplier?: number;
    /**
     * Suffix for the fine-tuned model name
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    suffix?: string;
    /**
     * Path to dataset for OpenAI backend
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    openaiDatasetPath?: string;
    /**
     * Path to dataset for HuggingFace backend
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    huggingfaceDatasetPath?: string;
    /**
     * HuggingFace repository ID (e.g. username/model-name)
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    hfRepoId?: string;
    /**
     * HuggingFace training framework
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    hfFramework?: SubmitTrainingJobRequestHfFrameworkEnum;
    /**
     * Path to local training script for Local backend
     * @type {string}
     * @memberof SubmitTrainingJobRequest
     */
    localScript?: string;
    /**
     * GPU device ID for Local backend
     * @type {number}
     * @memberof SubmitTrainingJobRequest
     */
    localGpuDevice?: number;
}


/**
 * @export
 */
export const SubmitTrainingJobRequestBackendEnum = {
    Openai: 'openai',
    Huggingface: 'huggingface',
    Local: 'local',
    DryRun: 'dry-run'
} as const;
export type SubmitTrainingJobRequestBackendEnum = typeof SubmitTrainingJobRequestBackendEnum[keyof typeof SubmitTrainingJobRequestBackendEnum];

/**
 * @export
 */
export const SubmitTrainingJobRequestHfFrameworkEnum = {
    Autotrain: 'autotrain',
    Trl: 'trl',
    Unsloth: 'unsloth'
} as const;
export type SubmitTrainingJobRequestHfFrameworkEnum = typeof SubmitTrainingJobRequestHfFrameworkEnum[keyof typeof SubmitTrainingJobRequestHfFrameworkEnum];


/**
 * Check if a given object implements the SubmitTrainingJobRequest interface.
 */
export function instanceOfSubmitTrainingJobRequest(value: object): value is SubmitTrainingJobRequest {
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('backend' in value) || value['backend'] === undefined) return false;
    return true;
}

export function SubmitTrainingJobRequestFromJSON(json: any): SubmitTrainingJobRequest {
    return SubmitTrainingJobRequestFromJSONTyped(json, false);
}

export function SubmitTrainingJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitTrainingJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'backend': json['backend'],
        'nEpochs': json['nEpochs'] == null ? undefined : json['nEpochs'],
        'batchSize': json['batchSize'] == null ? undefined : json['batchSize'],
        'learningRateMultiplier': json['learningRateMultiplier'] == null ? undefined : json['learningRateMultiplier'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'openaiDatasetPath': json['openaiDatasetPath'] == null ? undefined : json['openaiDatasetPath'],
        'huggingfaceDatasetPath': json['huggingfaceDatasetPath'] == null ? undefined : json['huggingfaceDatasetPath'],
        'hfRepoId': json['hfRepoId'] == null ? undefined : json['hfRepoId'],
        'hfFramework': json['hfFramework'] == null ? undefined : json['hfFramework'],
        'localScript': json['localScript'] == null ? undefined : json['localScript'],
        'localGpuDevice': json['localGpuDevice'] == null ? undefined : json['localGpuDevice'],
    };
}

export function SubmitTrainingJobRequestToJSON(json: any): SubmitTrainingJobRequest {
    return SubmitTrainingJobRequestToJSONTyped(json, false);
}

export function SubmitTrainingJobRequestToJSONTyped(value?: SubmitTrainingJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'backend': value['backend'],
        'nEpochs': value['nEpochs'],
        'batchSize': value['batchSize'],
        'learningRateMultiplier': value['learningRateMultiplier'],
        'suffix': value['suffix'],
        'openaiDatasetPath': value['openaiDatasetPath'],
        'huggingfaceDatasetPath': value['huggingfaceDatasetPath'],
        'hfRepoId': value['hfRepoId'],
        'hfFramework': value['hfFramework'],
        'localScript': value['localScript'],
        'localGpuDevice': value['localGpuDevice'],
    };
}

