/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FineTuningJob } from './FineTuningJob';
import {
    FineTuningJobFromJSON,
    FineTuningJobFromJSONTyped,
    FineTuningJobToJSON,
    FineTuningJobToJSONTyped,
} from './FineTuningJob';

/**
 * 
 * @export
 * @interface SubmitTrainingJob201Response
 */
export interface SubmitTrainingJob201Response {
    /**
     * 
     * @type {boolean}
     * @memberof SubmitTrainingJob201Response
     */
    success?: boolean;
    /**
     * 
     * @type {FineTuningJob}
     * @memberof SubmitTrainingJob201Response
     */
    job?: FineTuningJob;
}

/**
 * Check if a given object implements the SubmitTrainingJob201Response interface.
 */
export function instanceOfSubmitTrainingJob201Response(value: object): value is SubmitTrainingJob201Response {
    return true;
}

export function SubmitTrainingJob201ResponseFromJSON(json: any): SubmitTrainingJob201Response {
    return SubmitTrainingJob201ResponseFromJSONTyped(json, false);
}

export function SubmitTrainingJob201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitTrainingJob201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'job': json['job'] == null ? undefined : FineTuningJobFromJSON(json['job']),
    };
}

export function SubmitTrainingJob201ResponseToJSON(json: any): SubmitTrainingJob201Response {
    return SubmitTrainingJob201ResponseToJSONTyped(json, false);
}

export function SubmitTrainingJob201ResponseToJSONTyped(value?: SubmitTrainingJob201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'job': FineTuningJobToJSON(value['job']),
    };
}

