/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    avatarUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof UserProfileUpdate
     */
    userMetadata?: object;
}

/**
 * Check if a given object implements the UserProfileUpdate interface.
 */
export function instanceOfUserProfileUpdate(value: object): value is UserProfileUpdate {
    return true;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'userMetadata': json['userMetadata'] == null ? undefined : json['userMetadata'],
    };
}

export function UserProfileUpdateToJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateToJSONTyped(json, false);
}

export function UserProfileUpdateToJSONTyped(value?: UserProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullName': value['fullName'],
        'avatarUrl': value['avatarUrl'],
        'userMetadata': value['userMetadata'],
    };
}

