/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPreferencesNotifications } from './UserPreferencesNotifications';
import {
    UserPreferencesNotificationsFromJSON,
    UserPreferencesNotificationsFromJSONTyped,
    UserPreferencesNotificationsToJSON,
    UserPreferencesNotificationsToJSONTyped,
} from './UserPreferencesNotifications';

/**
 * 
 * @export
 * @interface UserPreferencesUpdate
 */
export interface UserPreferencesUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserPreferencesUpdate
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPreferencesUpdate
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPreferencesUpdate
     */
    timezone?: string;
    /**
     * 
     * @type {UserPreferencesNotifications}
     * @memberof UserPreferencesUpdate
     */
    notifications?: UserPreferencesNotifications;
}

/**
 * Check if a given object implements the UserPreferencesUpdate interface.
 */
export function instanceOfUserPreferencesUpdate(value: object): value is UserPreferencesUpdate {
    return true;
}

export function UserPreferencesUpdateFromJSON(json: any): UserPreferencesUpdate {
    return UserPreferencesUpdateFromJSONTyped(json, false);
}

export function UserPreferencesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferencesUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'notifications': json['notifications'] == null ? undefined : UserPreferencesNotificationsFromJSON(json['notifications']),
    };
}

export function UserPreferencesUpdateToJSON(json: any): UserPreferencesUpdate {
    return UserPreferencesUpdateToJSONTyped(json, false);
}

export function UserPreferencesUpdateToJSONTyped(value?: UserPreferencesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'language': value['language'],
        'timezone': value['timezone'],
        'notifications': UserPreferencesNotificationsToJSON(value['notifications']),
    };
}

