/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPreferencesNotifications } from './UserPreferencesNotifications';
import {
    UserPreferencesNotificationsFromJSON,
    UserPreferencesNotificationsFromJSONTyped,
    UserPreferencesNotificationsToJSON,
    UserPreferencesNotificationsToJSONTyped,
} from './UserPreferencesNotifications';

/**
 * 
 * @export
 * @interface UserPreferences
 */
export interface UserPreferences {
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    theme?: UserPreferencesThemeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    timezone?: string;
    /**
     * 
     * @type {UserPreferencesNotifications}
     * @memberof UserPreferences
     */
    notifications?: UserPreferencesNotifications;
}


/**
 * @export
 */
export const UserPreferencesThemeEnum = {
    Light: 'light',
    Dark: 'dark',
    System: 'system'
} as const;
export type UserPreferencesThemeEnum = typeof UserPreferencesThemeEnum[keyof typeof UserPreferencesThemeEnum];


/**
 * Check if a given object implements the UserPreferences interface.
 */
export function instanceOfUserPreferences(value: object): value is UserPreferences {
    return true;
}

export function UserPreferencesFromJSON(json: any): UserPreferences {
    return UserPreferencesFromJSONTyped(json, false);
}

export function UserPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'notifications': json['notifications'] == null ? undefined : UserPreferencesNotificationsFromJSON(json['notifications']),
    };
}

export function UserPreferencesToJSON(json: any): UserPreferences {
    return UserPreferencesToJSONTyped(json, false);
}

export function UserPreferencesToJSONTyped(value?: UserPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'language': value['language'],
        'timezone': value['timezone'],
        'notifications': UserPreferencesNotificationsToJSON(value['notifications']),
    };
}

