/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PublicMemory } from './V1PublicMemory';
import {
    V1PublicMemoryFromJSON,
    V1PublicMemoryFromJSONTyped,
    V1PublicMemoryToJSON,
    V1PublicMemoryToJSONTyped,
} from './V1PublicMemory';

/**
 * 
 * @export
 * @interface V1CreateMemoryResponse
 */
export interface V1CreateMemoryResponse {
    /**
     * 
     * @type {V1PublicMemory}
     * @memberof V1CreateMemoryResponse
     */
    data: V1PublicMemory;
}

/**
 * Check if a given object implements the V1CreateMemoryResponse interface.
 */
export function instanceOfV1CreateMemoryResponse(value: object): value is V1CreateMemoryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function V1CreateMemoryResponseFromJSON(json: any): V1CreateMemoryResponse {
    return V1CreateMemoryResponseFromJSONTyped(json, false);
}

export function V1CreateMemoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateMemoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': V1PublicMemoryFromJSON(json['data']),
    };
}

export function V1CreateMemoryResponseToJSON(json: any): V1CreateMemoryResponse {
    return V1CreateMemoryResponseToJSONTyped(json, false);
}

export function V1CreateMemoryResponseToJSONTyped(value?: V1CreateMemoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V1PublicMemoryToJSON(value['data']),
    };
}

