/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Error
 */
export interface V1Error {
    /**
     * Stable machine-readable code. One of:
     * `bad_request`, `validation_failed`, `unauthorized`,
     * `forbidden`, `not_found`, `conflict`, `payload_too_large`,
     * `rate_limited`, `internal_error`, `upstream_unavailable`,
     * `upstream_timeout`.
     * 
     * @type {string}
     * @memberof V1Error
     */
    error: string;
    /**
     * Human-readable message. Safe to display to end users.
     * @type {string}
     * @memberof V1Error
     */
    message: string;
}

/**
 * Check if a given object implements the V1Error interface.
 */
export function instanceOfV1Error(value: object): value is V1Error {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function V1ErrorFromJSON(json: any): V1Error {
    return V1ErrorFromJSONTyped(json, false);
}

export function V1ErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Error {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'message': json['message'],
    };
}

export function V1ErrorToJSON(json: any): V1Error {
    return V1ErrorToJSONTyped(json, false);
}

export function V1ErrorToJSONTyped(value?: V1Error | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

