/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1MemoryScope } from './V1MemoryScope';
import {
    V1MemoryScopeFromJSON,
    V1MemoryScopeFromJSONTyped,
    V1MemoryScopeToJSON,
    V1MemoryScopeToJSONTyped,
} from './V1MemoryScope';
import type { V1RetentionPolicy } from './V1RetentionPolicy';
import {
    V1RetentionPolicyFromJSON,
    V1RetentionPolicyFromJSONTyped,
    V1RetentionPolicyToJSON,
    V1RetentionPolicyToJSONTyped,
} from './V1RetentionPolicy';

/**
 * The public v1 memory record. This is a strict subset of the
 * internal `UnifiedMemory` type — internal fields (e.g. `vectorId`,
 * `emotionalContext`, `empathyMetrics`, `bankId`, `sourceService`)
 * are deliberately omitted.
 * 
 * @export
 * @interface V1PublicMemory
 */
export interface V1PublicMemory {
    /**
     * 
     * @type {string}
     * @memberof V1PublicMemory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1PublicMemory
     */
    content: string;
    /**
     * 
     * @type {V1MemoryScope}
     * @memberof V1PublicMemory
     */
    scope: V1MemoryScope;
    /**
     * 
     * @type {V1RetentionPolicy}
     * @memberof V1PublicMemory
     */
    retention: V1RetentionPolicy;
    /**
     * 
     * @type {string}
     * @memberof V1PublicMemory
     */
    category: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1PublicMemory
     */
    tags: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof V1PublicMemory
     */
    version: number;
    /**
     * 
     * @type {number}
     * @memberof V1PublicMemory
     */
    importance: number;
    /**
     * 
     * @type {Date}
     * @memberof V1PublicMemory
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1PublicMemory
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the V1PublicMemory interface.
 */
export function instanceOfV1PublicMemory(value: object): value is V1PublicMemory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('retention' in value) || value['retention'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('importance' in value) || value['importance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function V1PublicMemoryFromJSON(json: any): V1PublicMemory {
    return V1PublicMemoryFromJSONTyped(json, false);
}

export function V1PublicMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PublicMemory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'scope': V1MemoryScopeFromJSON(json['scope']),
        'retention': V1RetentionPolicyFromJSON(json['retention']),
        'category': json['category'],
        'tags': json['tags'],
        'version': json['version'],
        'importance': json['importance'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function V1PublicMemoryToJSON(json: any): V1PublicMemory {
    return V1PublicMemoryToJSONTyped(json, false);
}

export function V1PublicMemoryToJSONTyped(value?: V1PublicMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'scope': V1MemoryScopeToJSON(value['scope']),
        'retention': V1RetentionPolicyToJSON(value['retention']),
        'category': value['category'],
        'tags': value['tags'],
        'version': value['version'],
        'importance': value['importance'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

