/* tslint:disable */
/* eslint-disable */
/**
 * Pixelated Empathy API
 * The Pixelated Empathy API provides programmatic access to the platform\'s core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@pixelatedempathy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1MemoryScope } from './V1MemoryScope';
import {
    V1MemoryScopeFromJSON,
    V1MemoryScopeFromJSONTyped,
    V1MemoryScopeToJSON,
    V1MemoryScopeToJSONTyped,
} from './V1MemoryScope';
import type { V1RetentionPolicy } from './V1RetentionPolicy';
import {
    V1RetentionPolicyFromJSON,
    V1RetentionPolicyFromJSONTyped,
    V1RetentionPolicyToJSON,
    V1RetentionPolicyToJSONTyped,
} from './V1RetentionPolicy';

/**
 * 
 * @export
 * @interface V1UpdateMemoryRequest
 */
export interface V1UpdateMemoryRequest {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateMemoryRequest
     */
    content: string;
    /**
     * 
     * @type {V1MemoryScope}
     * @memberof V1UpdateMemoryRequest
     */
    scope?: V1MemoryScope;
    /**
     * 
     * @type {V1RetentionPolicy}
     * @memberof V1UpdateMemoryRequest
     */
    retention?: V1RetentionPolicy;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateMemoryRequest
     */
    category?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpdateMemoryRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof V1UpdateMemoryRequest
     */
    importance?: number;
}



/**
 * Check if a given object implements the V1UpdateMemoryRequest interface.
 */
export function instanceOfV1UpdateMemoryRequest(value: object): value is V1UpdateMemoryRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function V1UpdateMemoryRequestFromJSON(json: any): V1UpdateMemoryRequest {
    return V1UpdateMemoryRequestFromJSONTyped(json, false);
}

export function V1UpdateMemoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateMemoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'scope': json['scope'] == null ? undefined : V1MemoryScopeFromJSON(json['scope']),
        'retention': json['retention'] == null ? undefined : V1RetentionPolicyFromJSON(json['retention']),
        'category': json['category'] == null ? undefined : json['category'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'importance': json['importance'] == null ? undefined : json['importance'],
    };
}

export function V1UpdateMemoryRequestToJSON(json: any): V1UpdateMemoryRequest {
    return V1UpdateMemoryRequestToJSONTyped(json, false);
}

export function V1UpdateMemoryRequestToJSONTyped(value?: V1UpdateMemoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'scope': V1MemoryScopeToJSON(value['scope']),
        'retention': V1RetentionPolicyToJSON(value['retention']),
        'category': value['category'],
        'tags': value['tags'],
        'importance': value['importance'],
    };
}

