// Crisis keyword configuration for cultural/idiomatic edge cases and euphemisms
// Merges built-in patterns with auto-generated cultural/15k datasets from Python integrator.

// Generated by edge_case_integrator.py. The file is committed (an empty
// placeholder before the integrator first runs), so it can be imported
// statically — no runtime loading needed. The previous implementation called
// globalThis.require, which does not exist in ESM and always failed, so the
// generated sets never loaded anywhere.
import {
  SUICIDE_EUPHEMISMS as GENERATED_SUICIDE_EUPHEMISMS,
  SAFE_IDIOMATIC_EXCLUSIONS as GENERATED_SAFE_IDIOMATIC_EXCLUSIONS,
} from "./generated.keywords";

// Built-in suicide euphemisms (conservative base set)
const BUILTIN_SUICIDE_EUPHEMISMS: readonly string[] = [
  "unalive",
  "unalive myself",
  "don't want to live",
];

// Built-in safe idiomatic exclusions (conservative regex patterns)
const BUILTIN_SAFE_IDIOMATIC_EXCLUSIONS: readonly RegExp[] = [
  /\bkill(?:ed|ing)?\s+it\b/i, // "we killed it at the show"
  /\b(dying|die|died)\s+to\b/i, // "dying to see you"
  /\bdie of (?:laughter|laughing|boredom)\b/i,
  /\bsuicide\s+squad\b/i, // movie reference
  /\b(homework|traffic|commute|deadline|exam|emoji)\s+is\s+killing\s+me\b/i,
  /\b(?:reading|studying|learning|talking)\s+about\s+suicide\b/i,
  /\b(?:watch(?:ing)?|saw)\s+(?:a\s+)?(?:movie|film|article)\s+about\s+suicide\b/i,
];

/**
 * Merged suicide euphemisms: built-ins + auto-generated from cultural datasets
 * Supports up to 15k+ curated entries once Python integrator populates generated.keywords.ts
 */
export const SUICIDE_EUPHEMISMS: readonly string[] = [
  ...BUILTIN_SUICIDE_EUPHEMISMS,
  ...GENERATED_SUICIDE_EUPHEMISMS,
];

/**
 * Merged safe idiomatic exclusions: built-ins + auto-generated from cultural datasets
 * Keeps patterns conservative to avoid suppressing real crisis signals.
 */
export const SAFE_IDIOMATIC_EXCLUSIONS: readonly RegExp[] = [
  ...BUILTIN_SAFE_IDIOMATIC_EXCLUSIONS,
  ...GENERATED_SAFE_IDIOMATIC_EXCLUSIONS,
];
