/**
 * Vocabulary data for encrypted text processing.
 * Extracted from encrypted-text-processor.ts; pure data, no runtime deps.
 */

/**
 * Vocabulary for sentiment analysis — maps words to sentiment scores.
 * Positive words → positive scores, negative words → negative scores.
 * This is the plaintext weight vector that gets multiplied with the
 * encrypted word frequency vector.
 */
export const SENTIMENT_VOCABULARY: Record<string, number> = {
  good: 1,
  great: 2,
  excellent: 3,
  happy: 2,
  joy: 2,
  love: 3,
  wonderful: 3,
  amazing: 3,
  fantastic: 3,
  positive: 1,
  hope: 1,
  grateful: 2,
  thankful: 2,
  calm: 1,
  peace: 1,
  better: 1,
  improve: 1,
  progress: 1,
  success: 2,
  confident: 2,
  strong: 1,
  proud: 2,
  bad: -1,
  terrible: -3,
  awful: -3,
  horrible: -3,
  sad: -2,
  depression: -2,
  angry: -2,
  anger: -2,
  fear: -2,
  anxious: -2,
  anxiety: -2,
  hopeless: -3,
  helpless: -2,
  pain: -2,
  hurt: -2,
  broken: -2,
  lost: -1,
  lonely: -2,
  scared: -2,
  worried: -1,
  stress: -1,
  negative: -1,
  worse: -1,
  fail: -1,
  death: -2,
  suicide: -3,
  kill: -3,
  die: -2,
}

/**
 * Category keywords for categorization.
 * Each category has a set of keywords with weights.
 */
export const CATEGORY_VOCABULARY: Record<string, Record<string, number>> = {
  anxiety: {
    anxious: 3,
    anxiety: 3,
    worry: 2,
    worried: 2,
    fear: 2,
    panic: 3,
    stress: 1,
    nervous: 2,
    scared: 2,
    afraid: 2,
  },
  depression: {
    sad: 3,
    depression: 3,
    hopeless: 3,
    empty: 2,
    tired: 1,
    numb: 2,
    meaningless: 2,
    worthless: 3,
    guilty: 2,
    alone: 2,
  },
  trauma: {
    trauma: 3,
    flashback: 3,
    nightmare: 2,
    abuse: 3,
    assault: 3,
    hurt: 1,
    victim: 2,
    ptsd: 3,
    trigger: 2,
    painful: 2,
  },
  relationship: {
    relationship: 3,
    partner: 2,
    marriage: 2,
    divorce: 2,
    conflict: 2,
    family: 1,
    couple: 2,
    trust: 1,
    communication: 1,
    boundary: 2,
  },
  substance_use: {
    drink: 2,
    drinking: 3,
    alcohol: 3,
    drugs: 3,
    addiction: 3,
    sober: 2,
    withdrawal: 3,
    relapse: 3,
    substance: 3,
    drunk: 2,
  },
  general: {
    feeling: 1,
    think: 1,
    life: 1,
    people: 1,
    work: 1,
    time: 1,
    help: 1,
    want: 1,
    need: 1,
    things: 1,
  },
}

