/**
 * Edge Computing Manager - Cloudflare Edge Locations (Part 2)
 *
 * Cloudflare edge locations: Madrid through Nuremberg.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const CLOUDFLARE_EDGE_LOCATIONS_2: EdgeLocation[] = [
  {
    id: 'edge-cf-madrid',
    name: 'Cloudflare Madrid',
    city: 'Madrid',
    country: 'Spain',
    continent: 'Europe',
    coordinates: { latitude: 40.4168, longitude: -3.7038 },
    provider: 'cloudflare',
    region: 'europe-southwest1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-paris',
    name: 'Cloudflare Paris',
    city: 'Paris',
    country: 'France',
    continent: 'Europe',
    coordinates: { latitude: 48.8566, longitude: 2.3522 },
    provider: 'cloudflare',
    region: 'europe-west9',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-berlin',
    name: 'Cloudflare Berlin',
    city: 'Berlin',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 52.52, longitude: 13.405 },
    provider: 'cloudflare',
    region: 'europe-central3',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-copenhagen',
    name: 'Cloudflare Copenhagen',
    city: 'Copenhagen',
    country: 'Denmark',
    continent: 'Europe',
    coordinates: { latitude: 55.6761, longitude: 12.5683 },
    provider: 'cloudflare',
    region: 'europe-north2',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-helsinki',
    name: 'Cloudflare Helsinki',
    city: 'Helsinki',
    country: 'Finland',
    continent: 'Europe',
    coordinates: { latitude: 60.1699, longitude: 24.9384 },
    provider: 'cloudflare',
    region: 'europe-north3',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-oslo',
    name: 'Cloudflare Oslo',
    city: 'Oslo',
    country: 'Norway',
    continent: 'Europe',
    coordinates: { latitude: 59.9139, longitude: 10.7522 },
    provider: 'cloudflare',
    region: 'europe-north4',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-dublin',
    name: 'Cloudflare Dublin',
    city: 'Dublin',
    country: 'Ireland',
    continent: 'Europe',
    coordinates: { latitude: 53.3498, longitude: -6.2603 },
    provider: 'cloudflare',
    region: 'europe-west2',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-lisbon',
    name: 'Cloudflare Lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
    coordinates: { latitude: 38.7223, longitude: -9.1393 },
    provider: 'cloudflare',
    region: 'europe-southwest2',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-athens',
    name: 'Cloudflare Athens',
    city: 'Athens',
    country: 'Greece',
    continent: 'Europe',
    coordinates: { latitude: 37.9838, longitude: 23.7275 },
    provider: 'cloudflare',
    region: 'europe-south3',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bucharest',
    name: 'Cloudflare Bucharest',
    city: 'Bucharest',
    country: 'Romania',
    continent: 'Europe',
    coordinates: { latitude: 44.4268, longitude: 26.1025 },
    provider: 'cloudflare',
    region: 'europe-central4',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-prague',
    name: 'Cloudflare Prague',
    city: 'Prague',
    country: 'Czech Republic',
    continent: 'Europe',
    coordinates: { latitude: 50.0755, longitude: 14.4378 },
    provider: 'cloudflare',
    region: 'europe-central5',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-budapest',
    name: 'Cloudflare Budapest',
    city: 'Budapest',
    country: 'Hungary',
    continent: 'Europe',
    coordinates: { latitude: 47.4979, longitude: 19.0402 },
    provider: 'cloudflare',
    region: 'europe-central6',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-sophia',
    name: 'Cloudflare Sophia',
    city: 'Sophia Antipolis',
    country: 'France',
    continent: 'Europe',
    coordinates: { latitude: 43.6156, longitude: 7.0412 },
    provider: 'cloudflare',
    region: 'europe-south4',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-hamburg',
    name: 'Cloudflare Hamburg',
    city: 'Hamburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 53.5511, longitude: 9.9937 },
    provider: 'cloudflare',
    region: 'europe-central7',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-munich',
    name: 'Cloudflare Munich',
    city: 'Munich',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.1351, longitude: 11.582 },
    provider: 'cloudflare',
    region: 'europe-central8',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-cologne',
    name: 'Cloudflare Cologne',
    city: 'Cologne',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.9375, longitude: 6.9603 },
    provider: 'cloudflare',
    region: 'europe-central9',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-frankfurt',
    name: 'Cloudflare Frankfurt',
    city: 'Frankfurt',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.1109, longitude: 8.6821 },
    provider: 'cloudflare',
    region: 'europe-central10',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-stuttgart',
    name: 'Cloudflare Stuttgart',
    city: 'Stuttgart',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.7758, longitude: 9.1829 },
    provider: 'cloudflare',
    region: 'europe-central11',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-nuremberg',
    name: 'Cloudflare Nuremberg',
    city: 'Nuremberg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.4521, longitude: 11.0767 },
    provider: 'cloudflare',
    region: 'europe-central12',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
]
