/**
 * Edge Computing Manager - Cloudflare Edge Locations (Part 3)
 *
 * Cloudflare edge locations: Cloudflare Dusseldorf through Cloudflare Braunschweig.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const CLOUDFLARE_EDGE_LOCATIONS_3: EdgeLocation[] = [
  {
    id: 'edge-cf-dusseldorf',
    name: 'Cloudflare Dusseldorf',
    city: 'Dusseldorf',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.2277, longitude: 6.7735 },
    provider: 'cloudflare',
    region: 'europe-central13',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-leipzig',
    name: 'Cloudflare Leipzig',
    city: 'Leipzig',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.3397, longitude: 12.3731 },
    provider: 'cloudflare',
    region: 'europe-central14',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-dortmund',
    name: 'Cloudflare Dortmund',
    city: 'Dortmund',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.5136, longitude: 7.4653 },
    provider: 'cloudflare',
    region: 'europe-central15',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-essen',
    name: 'Cloudflare Essen',
    city: 'Essen',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.4556, longitude: 7.0116 },
    provider: 'cloudflare',
    region: 'europe-central16',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bremen',
    name: 'Cloudflare Bremen',
    city: 'Bremen',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 53.0793, longitude: 8.8017 },
    provider: 'cloudflare',
    region: 'europe-central17',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-hanover',
    name: 'Cloudflare Hanover',
    city: 'Hanover',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 52.3759, longitude: 9.732 },
    provider: 'cloudflare',
    region: 'europe-central18',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-dresden',
    name: 'Cloudflare Dresden',
    city: 'Dresden',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.0504, longitude: 13.7373 },
    provider: 'cloudflare',
    region: 'europe-central19',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-karlsruhe',
    name: 'Cloudflare Karlsruhe',
    city: 'Karlsruhe',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.0069, longitude: 8.4037 },
    provider: 'cloudflare',
    region: 'europe-central20',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bielefeld',
    name: 'Cloudflare Bielefeld',
    city: 'Bielefeld',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 52.0302, longitude: 8.5325 },
    provider: 'cloudflare',
    region: 'europe-central21',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-gelsenkirchen',
    name: 'Cloudflare Gelsenkirchen',
    city: 'Gelsenkirchen',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.473, longitude: 7.1208 },
    provider: 'cloudflare',
    region: 'europe-central22',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-wuppertal',
    name: 'Cloudflare Wuppertal',
    city: 'Wuppertal',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.2562, longitude: 7.1508 },
    provider: 'cloudflare',
    region: 'europe-central23',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bochum',
    name: 'Cloudflare Bochum',
    city: 'Bochum',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.4818, longitude: 7.2162 },
    provider: 'cloudflare',
    region: 'europe-central24',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-aachen',
    name: 'Cloudflare Aachen',
    city: 'Aachen',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.7753, longitude: 6.0839 },
    provider: 'cloudflare',
    region: 'europe-central25',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bonn',
    name: 'Cloudflare Bonn',
    city: 'Bonn',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.7374, longitude: 7.0982 },
    provider: 'cloudflare',
    region: 'europe-central26',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-mannheim',
    name: 'Cloudflare Mannheim',
    city: 'Mannheim',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.4875, longitude: 8.466 },
    provider: 'cloudflare',
    region: 'europe-central27',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-wiesbaden',
    name: 'Cloudflare Wiesbaden',
    city: 'Wiesbaden',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.0782, longitude: 8.2398 },
    provider: 'cloudflare',
    region: 'europe-central28',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-munster',
    name: 'Cloudflare Münster',
    city: 'Münster',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.9607, longitude: 7.6261 },
    provider: 'cloudflare',
    region: 'europe-central29',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-kiel',
    name: 'Cloudflare Kiel',
    city: 'Kiel',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 54.3233, longitude: 10.1228 },
    provider: 'cloudflare',
    region: 'europe-central30',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-braunschweig',
    name: 'Cloudflare Braunschweig',
    city: 'Braunschweig',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 52.2689, longitude: 10.5267 },
    provider: 'cloudflare',
    region: 'europe-central31',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
]
