/**
 * Edge Computing Manager - Cloudflare Edge Locations (Part 4)
 *
 * Cloudflare edge locations: Cloudflare Kassel through Cloudflare Bayreuth.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const CLOUDFLARE_EDGE_LOCATIONS_4: EdgeLocation[] = [
  {
    id: 'edge-cf-kassel',
    name: 'Cloudflare Kassel',
    city: 'Kassel',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.3127, longitude: 9.4797 },
    provider: 'cloudflare',
    region: 'europe-central32',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-augsburg',
    name: 'Cloudflare Augsburg',
    city: 'Augsburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.3705, longitude: 10.8978 },
    provider: 'cloudflare',
    region: 'europe-central33',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-freiburg',
    name: 'Cloudflare Freiburg',
    city: 'Freiburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 47.999, longitude: 7.8421 },
    provider: 'cloudflare',
    region: 'europe-central34',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-regensburg',
    name: 'Cloudflare Regensburg',
    city: 'Regensburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.0134, longitude: 12.1016 },
    provider: 'cloudflare',
    region: 'europe-central35',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-wurzburg',
    name: 'Cloudflare Würzburg',
    city: 'Würzburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.7913, longitude: 9.9534 },
    provider: 'cloudflare',
    region: 'europe-central36',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-ulm',
    name: 'Cloudflare Ulm',
    city: 'Ulm',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.4011, longitude: 9.9876 },
    provider: 'cloudflare',
    region: 'europe-central37',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-ingolstadt',
    name: 'Cloudflare Ingolstadt',
    city: 'Ingolstadt',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.7651, longitude: 11.4237 },
    provider: 'cloudflare',
    region: 'europe-central38',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-heilbronn',
    name: 'Cloudflare Heilbronn',
    city: 'Heilbronn',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.1427, longitude: 9.2109 },
    provider: 'cloudflare',
    region: 'europe-central39',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-pforzheim',
    name: 'Cloudflare Pforzheim',
    city: 'Pforzheim',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.8922, longitude: 8.6946 },
    provider: 'cloudflare',
    region: 'europe-central40',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-offenbach',
    name: 'Cloudflare Offenbach',
    city: 'Offenbach',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.0956, longitude: 8.7765 },
    provider: 'cloudflare',
    region: 'europe-central41',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-wolfsburg',
    name: 'Cloudflare Wolfsburg',
    city: 'Wolfsburg',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 52.4275, longitude: 10.7806 },
    provider: 'cloudflare',
    region: 'europe-central42',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-gottingen',
    name: 'Cloudflare Göttingen',
    city: 'Göttingen',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 51.5413, longitude: 9.9158 },
    provider: 'cloudflare',
    region: 'europe-central43',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-koblenz',
    name: 'Cloudflare Koblenz',
    city: 'Koblenz',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.3569, longitude: 7.5889 },
    provider: 'cloudflare',
    region: 'europe-central44',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-mainz',
    name: 'Cloudflare Mainz',
    city: 'Mainz',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.9929, longitude: 8.2473 },
    provider: 'cloudflare',
    region: 'europe-central45',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-saarbrucken',
    name: 'Cloudflare Saarbrücken',
    city: 'Saarbrücken',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.2344, longitude: 6.9969 },
    provider: 'cloudflare',
    region: 'europe-central46',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-trier',
    name: 'Cloudflare Trier',
    city: 'Trier',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.7567, longitude: 6.6414 },
    provider: 'cloudflare',
    region: 'europe-central47',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-freiburg-im-breisgau',
    name: 'Cloudflare Freiburg im Breisgau',
    city: 'Freiburg im Breisgau',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 47.999, longitude: 7.8421 },
    provider: 'cloudflare',
    region: 'europe-central48',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-passau',
    name: 'Cloudflare Passau',
    city: 'Passau',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 48.5745, longitude: 13.4605 },
    provider: 'cloudflare',
    region: 'europe-central49',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-bayreuth',
    name: 'Cloudflare Bayreuth',
    city: 'Bayreuth',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 49.9456, longitude: 11.5713 },
    provider: 'cloudflare',
    region: 'europe-central50',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
]
