/**
 * Edge Computing Manager - Default Edge Locations
 *
 * Predefined edge locations covering 90+ global locations across
 * Cloudflare Workers and AWS Lambda@Edge.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const DEFAULT_EDGE_LOCATIONS: EdgeLocation[] = [
    // North America
    {
      id: 'edge-us-east-1',
      name: 'US East (N. Virginia)',
      city: 'Ashburn',
      country: 'USA',
      continent: 'North America',
      coordinates: { latitude: 39.0438, longitude: -77.4874 },
      provider: 'aws',
      region: 'us-east-1',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 5, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-us-west-2',
      name: 'US West (Oregon)',
      city: 'Boardman',
      country: 'USA',
      continent: 'North America',
      coordinates: { latitude: 45.8399, longitude: -119.7006 },
      provider: 'aws',
      region: 'us-west-2',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 8, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-ca-central-1',
      name: 'Canada (Central)',
      city: 'Montreal',
      country: 'Canada',
      continent: 'North America',
      coordinates: { latitude: 45.5017, longitude: -73.5673 },
      provider: 'aws',
      region: 'ca-central-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 15, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },

    // Europe
    {
      id: 'edge-eu-west-1',
      name: 'EU West (Ireland)',
      city: 'Dublin',
      country: 'Ireland',
      continent: 'Europe',
      coordinates: { latitude: 53.3498, longitude: -6.2603 },
      provider: 'aws',
      region: 'eu-west-1',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 10, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-eu-central-1',
      name: 'EU Central (Frankfurt)',
      city: 'Frankfurt',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.1109, longitude: 8.6821 },
      provider: 'aws',
      region: 'eu-central-1',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 8, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-eu-north-1',
      name: 'EU North (Stockholm)',
      city: 'Stockholm',
      country: 'Sweden',
      continent: 'Europe',
      coordinates: { latitude: 59.3293, longitude: 18.0686 },
      provider: 'aws',
      region: 'eu-north-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 20, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },
    {
      id: 'edge-eu-west-3',
      name: 'EU West (Paris)',
      city: 'Paris',
      country: 'France',
      continent: 'Europe',
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      provider: 'aws',
      region: 'eu-west-3',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 12, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },
    {
      id: 'edge-eu-south-1',
      name: 'EU South (Milan)',
      city: 'Milan',
      country: 'Italy',
      continent: 'Europe',
      coordinates: { latitude: 45.4642, longitude: 9.19 },
      provider: 'aws',
      region: 'eu-south-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 18, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },

    // Asia Pacific
    {
      id: 'edge-ap-southeast-1',
      name: 'AP Southeast (Singapore)',
      city: 'Singapore',
      country: 'Singapore',
      continent: 'Asia',
      coordinates: { latitude: 1.3521, longitude: 103.8198 },
      provider: 'aws',
      region: 'ap-southeast-1',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 5, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-ap-northeast-1',
      name: 'AP Northeast (Tokyo)',
      city: 'Tokyo',
      country: 'Japan',
      continent: 'Asia',
      coordinates: { latitude: 35.6762, longitude: 139.6503 },
      provider: 'aws',
      region: 'ap-northeast-1',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 8, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-ap-southeast-2',
      name: 'AP Southeast (Sydney)',
      city: 'Sydney',
      country: 'Australia',
      continent: 'Oceania',
      coordinates: { latitude: -33.8688, longitude: 151.2093 },
      provider: 'aws',
      region: 'ap-southeast-2',
      priority: 1,
      capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
      network: { bandwidth: '10Gbps', latency: 15, cdn: true },
      aiModels: ['threat-detection-v2', 'bias-detection-v1'],
      cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
    },
    {
      id: 'edge-ap-northeast-2',
      name: 'AP Northeast (Seoul)',
      city: 'Seoul',
      country: 'South Korea',
      continent: 'Asia',
      coordinates: { latitude: 37.5665, longitude: 126.978 },
      provider: 'aws',
      region: 'ap-northeast-2',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 12, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },
    {
      id: 'edge-ap-south-1',
      name: 'AP South (Mumbai)',
      city: 'Mumbai',
      country: 'India',
      continent: 'Asia',
      coordinates: { latitude: 19.076, longitude: 72.8777 },
      provider: 'aws',
      region: 'ap-south-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 25, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },
    {
      id: 'edge-ap-east-1',
      name: 'AP East (Hong Kong)',
      city: 'Hong Kong',
      country: 'Hong Kong',
      continent: 'Asia',
      coordinates: { latitude: 22.3193, longitude: 114.1694 },
      provider: 'aws',
      region: 'ap-east-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 10, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },

    // South America
    {
      id: 'edge-sa-east-1',
      name: 'SA East (São Paulo)',
      city: 'São Paulo',
      country: 'Brazil',
      continent: 'South America',
      coordinates: { latitude: -23.5505, longitude: -46.6333 },
      provider: 'aws',
      region: 'sa-east-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 30, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },

    // Middle East & Africa
    {
      id: 'edge-me-south-1',
      name: 'ME South (Bahrain)',
      city: 'Manama',
      country: 'Bahrain',
      continent: 'Asia',
      coordinates: { latitude: 26.0667, longitude: 50.5577 },
      provider: 'aws',
      region: 'me-south-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 35, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },
    {
      id: 'edge-af-south-1',
      name: 'AF South (Cape Town)',
      city: 'Cape Town',
      country: 'South Africa',
      continent: 'Africa',
      coordinates: { latitude: -33.9249, longitude: 18.4241 },
      provider: 'aws',
      region: 'af-south-1',
      priority: 2,
      capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
      network: { bandwidth: '5Gbps', latency: 40, cdn: true },
      aiModels: ['threat-detection-v2'],
      cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
    },

    // Cloudflare Edge Locations (additional 30+ locations)
    {
      id: 'edge-cf-amsterdam',
      name: 'Cloudflare Amsterdam',
      city: 'Amsterdam',
      country: 'Netherlands',
      continent: 'Europe',
      coordinates: { latitude: 52.3676, longitude: 4.9041 },
      provider: 'cloudflare',
      region: 'europe-west4',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-london',
      name: 'Cloudflare London',
      city: 'London',
      country: 'United Kingdom',
      continent: 'Europe',
      coordinates: { latitude: 51.5074, longitude: -0.1278 },
      provider: 'cloudflare',
      region: 'europe-west2',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-san-jose',
      name: 'Cloudflare San Jose',
      city: 'San Jose',
      country: 'USA',
      continent: 'North America',
      coordinates: { latitude: 37.3382, longitude: -121.8863 },
      provider: 'cloudflare',
      region: 'us-west1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 2, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-atlanta',
      name: 'Cloudflare Atlanta',
      city: 'Atlanta',
      country: 'USA',
      continent: 'North America',
      coordinates: { latitude: 33.749, longitude: -84.388 },
      provider: 'cloudflare',
      region: 'us-east1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 2, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-tokyo',
      name: 'Cloudflare Tokyo',
      city: 'Tokyo',
      country: 'Japan',
      continent: 'Asia',
      coordinates: { latitude: 35.6762, longitude: 139.6503 },
      provider: 'cloudflare',
      region: 'asia-northeast1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-sydney',
      name: 'Cloudflare Sydney',
      city: 'Sydney',
      country: 'Australia',
      continent: 'Oceania',
      coordinates: { latitude: -33.8688, longitude: 151.2093 },
      provider: 'cloudflare',
      region: 'australia-southeast1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-singapore',
      name: 'Cloudflare Singapore',
      city: 'Singapore',
      country: 'Singapore',
      continent: 'Asia',
      coordinates: { latitude: 1.3521, longitude: 103.8198 },
      provider: 'cloudflare',
      region: 'asia-southeast1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 2, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-mumbai',
      name: 'Cloudflare Mumbai',
      city: 'Mumbai',
      country: 'India',
      continent: 'Asia',
      coordinates: { latitude: 19.076, longitude: 72.8777 },
      provider: 'cloudflare',
      region: 'asia-south1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 5, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-sao-paulo',
      name: 'Cloudflare São Paulo',
      city: 'São Paulo',
      country: 'Brazil',
      continent: 'South America',
      coordinates: { latitude: -23.5505, longitude: -46.6333 },
      provider: 'cloudflare',
      region: 'southamerica-east1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 5, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-johannesburg',
      name: 'Cloudflare Johannesburg',
      city: 'Johannesburg',
      country: 'South Africa',
      continent: 'Africa',
      coordinates: { latitude: -26.2041, longitude: 28.0473 },
      provider: 'cloudflare',
      region: 'africa-south1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 8, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-dubai',
      name: 'Cloudflare Dubai',
      city: 'Dubai',
      country: 'UAE',
      continent: 'Asia',
      coordinates: { latitude: 25.2048, longitude: 55.2708 },
      provider: 'cloudflare',
      region: 'me-central1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 5, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-tel-aviv',
      name: 'Cloudflare Tel Aviv',
      city: 'Tel Aviv',
      country: 'Israel',
      continent: 'Asia',
      coordinates: { latitude: 32.0853, longitude: 34.7818 },
      provider: 'cloudflare',
      region: 'me-west1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-mexico-city',
      name: 'Cloudflare Mexico City',
      city: 'Mexico City',
      country: 'Mexico',
      continent: 'North America',
      coordinates: { latitude: 19.4326, longitude: -99.1332 },
      provider: 'cloudflare',
      region: 'northamerica-south1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 5, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-toronto',
      name: 'Cloudflare Toronto',
      city: 'Toronto',
      country: 'Canada',
      continent: 'North America',
      coordinates: { latitude: 43.6532, longitude: -79.3832 },
      provider: 'cloudflare',
      region: 'northamerica-northeast1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-stockholm',
      name: 'Cloudflare Stockholm',
      city: 'Stockholm',
      country: 'Sweden',
      continent: 'Europe',
      coordinates: { latitude: 59.3293, longitude: 18.0686 },
      provider: 'cloudflare',
      region: 'europe-north1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-warsaw',
      name: 'Cloudflare Warsaw',
      city: 'Warsaw',
      country: 'Poland',
      continent: 'Europe',
      coordinates: { latitude: 52.2297, longitude: 21.0122 },
      provider: 'cloudflare',
      region: 'europe-central1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-vienna',
      name: 'Cloudflare Vienna',
      city: 'Vienna',
      country: 'Austria',
      continent: 'Europe',
      coordinates: { latitude: 48.2082, longitude: 16.3738 },
      provider: 'cloudflare',
      region: 'europe-central2',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-brussels',
      name: 'Cloudflare Brussels',
      city: 'Brussels',
      country: 'Belgium',
      continent: 'Europe',
      coordinates: { latitude: 50.8503, longitude: 4.3517 },
      provider: 'cloudflare',
      region: 'europe-west1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-zurich',
      name: 'Cloudflare Zurich',
      city: 'Zurich',
      country: 'Switzerland',
      continent: 'Europe',
      coordinates: { latitude: 47.3769, longitude: 8.5417 },
      provider: 'cloudflare',
      region: 'europe-west6',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-milan',
      name: 'Cloudflare Milan',
      city: 'Milan',
      country: 'Italy',
      continent: 'Europe',
      coordinates: { latitude: 45.4642, longitude: 9.19 },
      provider: 'cloudflare',
      region: 'europe-west8',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-madrid',
      name: 'Cloudflare Madrid',
      city: 'Madrid',
      country: 'Spain',
      continent: 'Europe',
      coordinates: { latitude: 40.4168, longitude: -3.7038 },
      provider: 'cloudflare',
      region: 'europe-southwest1',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-paris',
      name: 'Cloudflare Paris',
      city: 'Paris',
      country: 'France',
      continent: 'Europe',
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      provider: 'cloudflare',
      region: 'europe-west9',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-berlin',
      name: 'Cloudflare Berlin',
      city: 'Berlin',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 52.52, longitude: 13.405 },
      provider: 'cloudflare',
      region: 'europe-central3',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-copenhagen',
      name: 'Cloudflare Copenhagen',
      city: 'Copenhagen',
      country: 'Denmark',
      continent: 'Europe',
      coordinates: { latitude: 55.6761, longitude: 12.5683 },
      provider: 'cloudflare',
      region: 'europe-north2',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-helsinki',
      name: 'Cloudflare Helsinki',
      city: 'Helsinki',
      country: 'Finland',
      continent: 'Europe',
      coordinates: { latitude: 60.1699, longitude: 24.9384 },
      provider: 'cloudflare',
      region: 'europe-north3',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-oslo',
      name: 'Cloudflare Oslo',
      city: 'Oslo',
      country: 'Norway',
      continent: 'Europe',
      coordinates: { latitude: 59.9139, longitude: 10.7522 },
      provider: 'cloudflare',
      region: 'europe-north4',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-dublin',
      name: 'Cloudflare Dublin',
      city: 'Dublin',
      country: 'Ireland',
      continent: 'Europe',
      coordinates: { latitude: 53.3498, longitude: -6.2603 },
      provider: 'cloudflare',
      region: 'europe-west2',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-lisbon',
      name: 'Cloudflare Lisbon',
      city: 'Lisbon',
      country: 'Portugal',
      continent: 'Europe',
      coordinates: { latitude: 38.7223, longitude: -9.1393 },
      provider: 'cloudflare',
      region: 'europe-southwest2',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-athens',
      name: 'Cloudflare Athens',
      city: 'Athens',
      country: 'Greece',
      continent: 'Europe',
      coordinates: { latitude: 37.9838, longitude: 23.7275 },
      provider: 'cloudflare',
      region: 'europe-south3',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bucharest',
      name: 'Cloudflare Bucharest',
      city: 'Bucharest',
      country: 'Romania',
      continent: 'Europe',
      coordinates: { latitude: 44.4268, longitude: 26.1025 },
      provider: 'cloudflare',
      region: 'europe-central4',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-prague',
      name: 'Cloudflare Prague',
      city: 'Prague',
      country: 'Czech Republic',
      continent: 'Europe',
      coordinates: { latitude: 50.0755, longitude: 14.4378 },
      provider: 'cloudflare',
      region: 'europe-central5',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-budapest',
      name: 'Cloudflare Budapest',
      city: 'Budapest',
      country: 'Hungary',
      continent: 'Europe',
      coordinates: { latitude: 47.4979, longitude: 19.0402 },
      provider: 'cloudflare',
      region: 'europe-central6',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-sophia',
      name: 'Cloudflare Sophia',
      city: 'Sophia Antipolis',
      country: 'France',
      continent: 'Europe',
      coordinates: { latitude: 43.6156, longitude: 7.0412 },
      provider: 'cloudflare',
      region: 'europe-south4',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-hamburg',
      name: 'Cloudflare Hamburg',
      city: 'Hamburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 53.5511, longitude: 9.9937 },
      provider: 'cloudflare',
      region: 'europe-central7',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-munich',
      name: 'Cloudflare Munich',
      city: 'Munich',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.1351, longitude: 11.582 },
      provider: 'cloudflare',
      region: 'europe-central8',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-cologne',
      name: 'Cloudflare Cologne',
      city: 'Cologne',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.9375, longitude: 6.9603 },
      provider: 'cloudflare',
      region: 'europe-central9',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-frankfurt',
      name: 'Cloudflare Frankfurt',
      city: 'Frankfurt',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.1109, longitude: 8.6821 },
      provider: 'cloudflare',
      region: 'europe-central10',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-stuttgart',
      name: 'Cloudflare Stuttgart',
      city: 'Stuttgart',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.7758, longitude: 9.1829 },
      provider: 'cloudflare',
      region: 'europe-central11',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-nuremberg',
      name: 'Cloudflare Nuremberg',
      city: 'Nuremberg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.4521, longitude: 11.0767 },
      provider: 'cloudflare',
      region: 'europe-central12',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-dusseldorf',
      name: 'Cloudflare Dusseldorf',
      city: 'Dusseldorf',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.2277, longitude: 6.7735 },
      provider: 'cloudflare',
      region: 'europe-central13',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-leipzig',
      name: 'Cloudflare Leipzig',
      city: 'Leipzig',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.3397, longitude: 12.3731 },
      provider: 'cloudflare',
      region: 'europe-central14',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-dortmund',
      name: 'Cloudflare Dortmund',
      city: 'Dortmund',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.5136, longitude: 7.4653 },
      provider: 'cloudflare',
      region: 'europe-central15',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-essen',
      name: 'Cloudflare Essen',
      city: 'Essen',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.4556, longitude: 7.0116 },
      provider: 'cloudflare',
      region: 'europe-central16',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bremen',
      name: 'Cloudflare Bremen',
      city: 'Bremen',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 53.0793, longitude: 8.8017 },
      provider: 'cloudflare',
      region: 'europe-central17',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-hanover',
      name: 'Cloudflare Hanover',
      city: 'Hanover',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 52.3759, longitude: 9.732 },
      provider: 'cloudflare',
      region: 'europe-central18',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-dresden',
      name: 'Cloudflare Dresden',
      city: 'Dresden',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.0504, longitude: 13.7373 },
      provider: 'cloudflare',
      region: 'europe-central19',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-karlsruhe',
      name: 'Cloudflare Karlsruhe',
      city: 'Karlsruhe',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.0069, longitude: 8.4037 },
      provider: 'cloudflare',
      region: 'europe-central20',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bielefeld',
      name: 'Cloudflare Bielefeld',
      city: 'Bielefeld',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 52.0302, longitude: 8.5325 },
      provider: 'cloudflare',
      region: 'europe-central21',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-gelsenkirchen',
      name: 'Cloudflare Gelsenkirchen',
      city: 'Gelsenkirchen',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.473, longitude: 7.1208 },
      provider: 'cloudflare',
      region: 'europe-central22',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-wuppertal',
      name: 'Cloudflare Wuppertal',
      city: 'Wuppertal',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.2562, longitude: 7.1508 },
      provider: 'cloudflare',
      region: 'europe-central23',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bochum',
      name: 'Cloudflare Bochum',
      city: 'Bochum',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.4818, longitude: 7.2162 },
      provider: 'cloudflare',
      region: 'europe-central24',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-aachen',
      name: 'Cloudflare Aachen',
      city: 'Aachen',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.7753, longitude: 6.0839 },
      provider: 'cloudflare',
      region: 'europe-central25',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bonn',
      name: 'Cloudflare Bonn',
      city: 'Bonn',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.7374, longitude: 7.0982 },
      provider: 'cloudflare',
      region: 'europe-central26',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-mannheim',
      name: 'Cloudflare Mannheim',
      city: 'Mannheim',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.4875, longitude: 8.466 },
      provider: 'cloudflare',
      region: 'europe-central27',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-wiesbaden',
      name: 'Cloudflare Wiesbaden',
      city: 'Wiesbaden',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.0782, longitude: 8.2398 },
      provider: 'cloudflare',
      region: 'europe-central28',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-munster',
      name: 'Cloudflare Münster',
      city: 'Münster',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.9607, longitude: 7.6261 },
      provider: 'cloudflare',
      region: 'europe-central29',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-kiel',
      name: 'Cloudflare Kiel',
      city: 'Kiel',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 54.3233, longitude: 10.1228 },
      provider: 'cloudflare',
      region: 'europe-central30',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-braunschweig',
      name: 'Cloudflare Braunschweig',
      city: 'Braunschweig',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 52.2689, longitude: 10.5267 },
      provider: 'cloudflare',
      region: 'europe-central31',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-kassel',
      name: 'Cloudflare Kassel',
      city: 'Kassel',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.3127, longitude: 9.4797 },
      provider: 'cloudflare',
      region: 'europe-central32',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-augsburg',
      name: 'Cloudflare Augsburg',
      city: 'Augsburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.3705, longitude: 10.8978 },
      provider: 'cloudflare',
      region: 'europe-central33',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-freiburg',
      name: 'Cloudflare Freiburg',
      city: 'Freiburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 47.999, longitude: 7.8421 },
      provider: 'cloudflare',
      region: 'europe-central34',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-regensburg',
      name: 'Cloudflare Regensburg',
      city: 'Regensburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.0134, longitude: 12.1016 },
      provider: 'cloudflare',
      region: 'europe-central35',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-wurzburg',
      name: 'Cloudflare Würzburg',
      city: 'Würzburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.7913, longitude: 9.9534 },
      provider: 'cloudflare',
      region: 'europe-central36',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-ulm',
      name: 'Cloudflare Ulm',
      city: 'Ulm',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.4011, longitude: 9.9876 },
      provider: 'cloudflare',
      region: 'europe-central37',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-ingolstadt',
      name: 'Cloudflare Ingolstadt',
      city: 'Ingolstadt',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.7651, longitude: 11.4237 },
      provider: 'cloudflare',
      region: 'europe-central38',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-heilbronn',
      name: 'Cloudflare Heilbronn',
      city: 'Heilbronn',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.1427, longitude: 9.2109 },
      provider: 'cloudflare',
      region: 'europe-central39',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-pforzheim',
      name: 'Cloudflare Pforzheim',
      city: 'Pforzheim',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.8922, longitude: 8.6946 },
      provider: 'cloudflare',
      region: 'europe-central40',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-offenbach',
      name: 'Cloudflare Offenbach',
      city: 'Offenbach',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.0956, longitude: 8.7765 },
      provider: 'cloudflare',
      region: 'europe-central41',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-wolfsburg',
      name: 'Cloudflare Wolfsburg',
      city: 'Wolfsburg',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 52.4275, longitude: 10.7806 },
      provider: 'cloudflare',
      region: 'europe-central42',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-gottingen',
      name: 'Cloudflare Göttingen',
      city: 'Göttingen',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 51.5413, longitude: 9.9158 },
      provider: 'cloudflare',
      region: 'europe-central43',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-koblenz',
      name: 'Cloudflare Koblenz',
      city: 'Koblenz',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 50.3569, longitude: 7.5889 },
      provider: 'cloudflare',
      region: 'europe-central44',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-mainz',
      name: 'Cloudflare Mainz',
      city: 'Mainz',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.9929, longitude: 8.2473 },
      provider: 'cloudflare',
      region: 'europe-central45',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-saarbrucken',
      name: 'Cloudflare Saarbrücken',
      city: 'Saarbrücken',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.2344, longitude: 6.9969 },
      provider: 'cloudflare',
      region: 'europe-central46',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-trier',
      name: 'Cloudflare Trier',
      city: 'Trier',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.7567, longitude: 6.6414 },
      provider: 'cloudflare',
      region: 'europe-central47',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-freiburg-im-breisgau',
      name: 'Cloudflare Freiburg im Breisgau',
      city: 'Freiburg im Breisgau',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 47.999, longitude: 7.8421 },
      provider: 'cloudflare',
      region: 'europe-central48',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-passau',
      name: 'Cloudflare Passau',
      city: 'Passau',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 48.5745, longitude: 13.4605 },
      provider: 'cloudflare',
      region: 'europe-central49',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
    {
      id: 'edge-cf-bayreuth',
      name: 'Cloudflare Bayreuth',
      city: 'Bayreuth',
      country: 'Germany',
      continent: 'Europe',
      coordinates: { latitude: 49.9456, longitude: 11.5713 },
      provider: 'cloudflare',
      region: 'europe-central50',
      priority: 1,
      capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
      network: { bandwidth: '100Gbps', latency: 3, cdn: true },
      aiModels: [
        'threat-detection-v2',
        'bias-detection-v1',
        'behavioral-analysis-v1',
      ],
      cacheConfig: {
        size: '500MB',
        ttl: 7200,
        strategies: ['LRU', 'LFU', 'ARC'],
      },
    },
  ]
