/**
 * Edge Computing Manager - Cloudflare Edge Locations (Part 1)
 *
 * Cloudflare edge locations: Amsterdam through Milan.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const CLOUDFLARE_EDGE_LOCATIONS_1: EdgeLocation[] = [
  {
    id: 'edge-cf-amsterdam',
    name: 'Cloudflare Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    continent: 'Europe',
    coordinates: { latitude: 52.3676, longitude: 4.9041 },
    provider: 'cloudflare',
    region: 'europe-west4',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-london',
    name: 'Cloudflare London',
    city: 'London',
    country: 'United Kingdom',
    continent: 'Europe',
    coordinates: { latitude: 51.5074, longitude: -0.1278 },
    provider: 'cloudflare',
    region: 'europe-west2',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-san-jose',
    name: 'Cloudflare San Jose',
    city: 'San Jose',
    country: 'USA',
    continent: 'North America',
    coordinates: { latitude: 37.3382, longitude: -121.8863 },
    provider: 'cloudflare',
    region: 'us-west1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 2, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-atlanta',
    name: 'Cloudflare Atlanta',
    city: 'Atlanta',
    country: 'USA',
    continent: 'North America',
    coordinates: { latitude: 33.749, longitude: -84.388 },
    provider: 'cloudflare',
    region: 'us-east1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 2, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-tokyo',
    name: 'Cloudflare Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    coordinates: { latitude: 35.6762, longitude: 139.6503 },
    provider: 'cloudflare',
    region: 'asia-northeast1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-sydney',
    name: 'Cloudflare Sydney',
    city: 'Sydney',
    country: 'Australia',
    continent: 'Oceania',
    coordinates: { latitude: -33.8688, longitude: 151.2093 },
    provider: 'cloudflare',
    region: 'australia-southeast1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-singapore',
    name: 'Cloudflare Singapore',
    city: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
    coordinates: { latitude: 1.3521, longitude: 103.8198 },
    provider: 'cloudflare',
    region: 'asia-southeast1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 2, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-mumbai',
    name: 'Cloudflare Mumbai',
    city: 'Mumbai',
    country: 'India',
    continent: 'Asia',
    coordinates: { latitude: 19.076, longitude: 72.8777 },
    provider: 'cloudflare',
    region: 'asia-south1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 5, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-sao-paulo',
    name: 'Cloudflare São Paulo',
    city: 'São Paulo',
    country: 'Brazil',
    continent: 'South America',
    coordinates: { latitude: -23.5505, longitude: -46.6333 },
    provider: 'cloudflare',
    region: 'southamerica-east1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 5, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-johannesburg',
    name: 'Cloudflare Johannesburg',
    city: 'Johannesburg',
    country: 'South Africa',
    continent: 'Africa',
    coordinates: { latitude: -26.2041, longitude: 28.0473 },
    provider: 'cloudflare',
    region: 'africa-south1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 8, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-dubai',
    name: 'Cloudflare Dubai',
    city: 'Dubai',
    country: 'UAE',
    continent: 'Asia',
    coordinates: { latitude: 25.2048, longitude: 55.2708 },
    provider: 'cloudflare',
    region: 'me-central1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 5, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-tel-aviv',
    name: 'Cloudflare Tel Aviv',
    city: 'Tel Aviv',
    country: 'Israel',
    continent: 'Asia',
    coordinates: { latitude: 32.0853, longitude: 34.7818 },
    provider: 'cloudflare',
    region: 'me-west1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-mexico-city',
    name: 'Cloudflare Mexico City',
    city: 'Mexico City',
    country: 'Mexico',
    continent: 'North America',
    coordinates: { latitude: 19.4326, longitude: -99.1332 },
    provider: 'cloudflare',
    region: 'northamerica-south1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 5, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-toronto',
    name: 'Cloudflare Toronto',
    city: 'Toronto',
    country: 'Canada',
    continent: 'North America',
    coordinates: { latitude: 43.6532, longitude: -79.3832 },
    provider: 'cloudflare',
    region: 'northamerica-northeast1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-stockholm',
    name: 'Cloudflare Stockholm',
    city: 'Stockholm',
    country: 'Sweden',
    continent: 'Europe',
    coordinates: { latitude: 59.3293, longitude: 18.0686 },
    provider: 'cloudflare',
    region: 'europe-north1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-warsaw',
    name: 'Cloudflare Warsaw',
    city: 'Warsaw',
    country: 'Poland',
    continent: 'Europe',
    coordinates: { latitude: 52.2297, longitude: 21.0122 },
    provider: 'cloudflare',
    region: 'europe-central1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-vienna',
    name: 'Cloudflare Vienna',
    city: 'Vienna',
    country: 'Austria',
    continent: 'Europe',
    coordinates: { latitude: 48.2082, longitude: 16.3738 },
    provider: 'cloudflare',
    region: 'europe-central2',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-brussels',
    name: 'Cloudflare Brussels',
    city: 'Brussels',
    country: 'Belgium',
    continent: 'Europe',
    coordinates: { latitude: 50.8503, longitude: 4.3517 },
    provider: 'cloudflare',
    region: 'europe-west1',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-zurich',
    name: 'Cloudflare Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    continent: 'Europe',
    coordinates: { latitude: 47.3769, longitude: 8.5417 },
    provider: 'cloudflare',
    region: 'europe-west6',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
  {
    id: 'edge-cf-milan',
    name: 'Cloudflare Milan',
    city: 'Milan',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { latitude: 45.4642, longitude: 9.19 },
    provider: 'cloudflare',
    region: 'europe-west8',
    priority: 1,
    capacity: { cpu: 4, memory: '1GB', storage: '20GB' },
    network: { bandwidth: '100Gbps', latency: 3, cdn: true },
    aiModels: [
      'threat-detection-v2',
      'bias-detection-v1',
      'behavioral-analysis-v1',
    ],
    cacheConfig: {
      size: '500MB',
      ttl: 7200,
      strategies: ['LRU', 'LFU', 'ARC'],
    },
  },
]
