/**
 * Edge Computing Manager - AWS Edge Locations
 *
 * Predefined AWS edge locations covering North America, Europe,
 * Asia Pacific, South America, Middle East & Africa.
 */

import type { EdgeLocation } from './EdgeComputingManager.types'

export const AWS_EDGE_LOCATIONS: EdgeLocation[] = [
  // North America
  {
    id: 'edge-us-east-1',
    name: 'US East (N. Virginia)',
    city: 'Ashburn',
    country: 'USA',
    continent: 'North America',
    coordinates: { latitude: 39.0438, longitude: -77.4874 },
    provider: 'aws',
    region: 'us-east-1',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 5, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-us-west-2',
    name: 'US West (Oregon)',
    city: 'Boardman',
    country: 'USA',
    continent: 'North America',
    coordinates: { latitude: 45.8399, longitude: -119.7006 },
    provider: 'aws',
    region: 'us-west-2',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 8, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-ca-central-1',
    name: 'Canada (Central)',
    city: 'Montreal',
    country: 'Canada',
    continent: 'North America',
    coordinates: { latitude: 45.5017, longitude: -73.5673 },
    provider: 'aws',
    region: 'ca-central-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 15, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },

  // Europe
  {
    id: 'edge-eu-west-1',
    name: 'EU West (Ireland)',
    city: 'Dublin',
    country: 'Ireland',
    continent: 'Europe',
    coordinates: { latitude: 53.3498, longitude: -6.2603 },
    provider: 'aws',
    region: 'eu-west-1',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 10, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-eu-central-1',
    name: 'EU Central (Frankfurt)',
    city: 'Frankfurt',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { latitude: 50.1109, longitude: 8.6821 },
    provider: 'aws',
    region: 'eu-central-1',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 8, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-eu-north-1',
    name: 'EU North (Stockholm)',
    city: 'Stockholm',
    country: 'Sweden',
    continent: 'Europe',
    coordinates: { latitude: 59.3293, longitude: 18.0686 },
    provider: 'aws',
    region: 'eu-north-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 20, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
  {
    id: 'edge-eu-west-3',
    name: 'EU West (Paris)',
    city: 'Paris',
    country: 'France',
    continent: 'Europe',
    coordinates: { latitude: 48.8566, longitude: 2.3522 },
    provider: 'aws',
    region: 'eu-west-3',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 12, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
  {
    id: 'edge-eu-south-1',
    name: 'EU South (Milan)',
    city: 'Milan',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { latitude: 45.4642, longitude: 9.19 },
    provider: 'aws',
    region: 'eu-south-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 18, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },

  // Asia Pacific
  {
    id: 'edge-ap-southeast-1',
    name: 'AP Southeast (Singapore)',
    city: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
    coordinates: { latitude: 1.3521, longitude: 103.8198 },
    provider: 'aws',
    region: 'ap-southeast-1',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 5, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-ap-northeast-1',
    name: 'AP Northeast (Tokyo)',
    city: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    coordinates: { latitude: 35.6762, longitude: 139.6503 },
    provider: 'aws',
    region: 'ap-northeast-1',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 8, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-ap-southeast-2',
    name: 'AP Southeast (Sydney)',
    city: 'Sydney',
    country: 'Australia',
    continent: 'Oceania',
    coordinates: { latitude: -33.8688, longitude: 151.2093 },
    provider: 'aws',
    region: 'ap-southeast-2',
    priority: 1,
    capacity: { cpu: 2, memory: '512MB', storage: '10GB' },
    network: { bandwidth: '10Gbps', latency: 15, cdn: true },
    aiModels: ['threat-detection-v2', 'bias-detection-v1'],
    cacheConfig: { size: '100MB', ttl: 3600, strategies: ['LRU', 'LFU'] },
  },
  {
    id: 'edge-ap-northeast-2',
    name: 'AP Northeast (Seoul)',
    city: 'Seoul',
    country: 'South Korea',
    continent: 'Asia',
    coordinates: { latitude: 37.5665, longitude: 126.978 },
    provider: 'aws',
    region: 'ap-northeast-2',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 12, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
  {
    id: 'edge-ap-south-1',
    name: 'AP South (Mumbai)',
    city: 'Mumbai',
    country: 'India',
    continent: 'Asia',
    coordinates: { latitude: 19.076, longitude: 72.8777 },
    provider: 'aws',
    region: 'ap-south-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 25, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
  {
    id: 'edge-ap-east-1',
    name: 'AP East (Hong Kong)',
    city: 'Hong Kong',
    country: 'Hong Kong',
    continent: 'Asia',
    coordinates: { latitude: 22.3193, longitude: 114.1694 },
    provider: 'aws',
    region: 'ap-east-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 10, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },

  // South America
  {
    id: 'edge-sa-east-1',
    name: 'SA East (São Paulo)',
    city: 'São Paulo',
    country: 'Brazil',
    continent: 'South America',
    coordinates: { latitude: -23.5505, longitude: -46.6333 },
    provider: 'aws',
    region: 'sa-east-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 30, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },

  // Middle East & Africa
  {
    id: 'edge-me-south-1',
    name: 'ME South (Bahrain)',
    city: 'Manama',
    country: 'Bahrain',
    continent: 'Asia',
    coordinates: { latitude: 26.0667, longitude: 50.5577 },
    provider: 'aws',
    region: 'me-south-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 35, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
  {
    id: 'edge-af-south-1',
    name: 'AF South (Cape Town)',
    city: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    coordinates: { latitude: -33.9249, longitude: 18.4241 },
    provider: 'aws',
    region: 'af-south-1',
    priority: 2,
    capacity: { cpu: 1, memory: '256MB', storage: '5GB' },
    network: { bandwidth: '5Gbps', latency: 40, cdn: true },
    aiModels: ['threat-detection-v2'],
    cacheConfig: { size: '50MB', ttl: 1800, strategies: ['LRU'] },
  },
]
