[project]
name = "deep-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dagger", email = "dagger@pixelated.love" }
]
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.6.8",
    "langchain-openai>=1.6.0",
    "langsmith>=0.11.2",
    "python-dotenv>=1.2.2",
    "tavily-python>=0.8.0",
]

[project.scripts]
deep-agent = "deep_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
