/**
 * EHR REST API v1 — Endpoint definitions.
 *
 * Maps each of the 7 endpoint groups to their FHIR R4 resource types
 * and RBAC permissions.
 */

import type { EndpointDefinition, EndpointGroup } from './types.js'

export const ENDPOINT_GROUPS: Record<EndpointGroup, EndpointDefinition[]> = {
  patients: [
    {
      method: 'GET',
      path: '/patients',
      resourceType: 'Patient',
      permission: 'read_patient',
      description: 'Search patients',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/patients/:id',
      resourceType: 'Patient',
      permission: 'read_patient',
      description: 'Read patient',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/patients',
      resourceType: 'Patient',
      permission: 'write_patient',
      description: 'Create patient',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/patients/:id',
      resourceType: 'Patient',
      permission: 'write_patient',
      description: 'Update patient',
      operation: 'update',
    },
    {
      method: 'DELETE',
      path: '/patients/:id',
      resourceType: 'Patient',
      permission: 'write_patient',
      description: 'Delete patient',
      operation: 'delete',
    },
  ],
  encounters: [
    {
      method: 'GET',
      path: '/encounters',
      resourceType: 'Encounter',
      permission: 'read_encounter',
      description: 'Search encounters',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/encounters/:id',
      resourceType: 'Encounter',
      permission: 'read_encounter',
      description: 'Read encounter',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/encounters',
      resourceType: 'Encounter',
      permission: 'write_encounter',
      description: 'Create encounter',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/encounters/:id',
      resourceType: 'Encounter',
      permission: 'write_encounter',
      description: 'Update encounter',
      operation: 'update',
    },
    {
      method: 'DELETE',
      path: '/encounters/:id',
      resourceType: 'Encounter',
      permission: 'write_encounter',
      description: 'Delete encounter',
      operation: 'delete',
    },
  ],
  appointments: [
    {
      method: 'GET',
      path: '/appointments',
      resourceType: 'Appointment',
      permission: 'read_schedule',
      description: 'Search appointments',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/appointments/:id',
      resourceType: 'Appointment',
      permission: 'read_schedule',
      description: 'Read appointment',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/appointments',
      resourceType: 'Appointment',
      permission: 'manage_schedule',
      description: 'Create appointment',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/appointments/:id',
      resourceType: 'Appointment',
      permission: 'manage_schedule',
      description: 'Update appointment',
      operation: 'update',
    },
    {
      method: 'DELETE',
      path: '/appointments/:id',
      resourceType: 'Appointment',
      permission: 'manage_schedule',
      description: 'Delete appointment',
      operation: 'delete',
    },
  ],
  notes: [
    {
      method: 'GET',
      path: '/notes',
      resourceType: 'DocumentReference',
      permission: 'read_clinical_note',
      description: 'Search clinical notes',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/notes/:id',
      resourceType: 'DocumentReference',
      permission: 'read_clinical_note',
      description: 'Read clinical note',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/notes',
      resourceType: 'DocumentReference',
      permission: 'write_clinical_note',
      description: 'Create clinical note',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/notes/:id',
      resourceType: 'DocumentReference',
      permission: 'write_clinical_note',
      description: 'Update clinical note',
      operation: 'update',
    },
  ],
  claims: [
    {
      method: 'GET',
      path: '/claims',
      resourceType: 'Claim',
      permission: 'read_claim',
      description: 'Search claims',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/claims/:id',
      resourceType: 'Claim',
      permission: 'read_claim',
      description: 'Read claim',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/claims',
      resourceType: 'Claim',
      permission: 'submit_claim',
      description: 'Submit claim',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/claims/:id',
      resourceType: 'Claim',
      permission: 'submit_claim',
      description: 'Update claim',
      operation: 'update',
    },
  ],
  consents: [
    {
      method: 'GET',
      path: '/consents',
      resourceType: 'Consent',
      permission: 'manage_consent',
      description: 'Search consents',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/consents/:id',
      resourceType: 'Consent',
      permission: 'manage_consent',
      description: 'Read consent',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/consents',
      resourceType: 'Consent',
      permission: 'manage_consent',
      description: 'Create consent',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/consents/:id',
      resourceType: 'Consent',
      permission: 'manage_consent',
      description: 'Update consent',
      operation: 'update',
    },
  ],
  observations: [
    {
      method: 'GET',
      path: '/observations',
      resourceType: 'Observation',
      permission: 'read_observation',
      description: 'Search observations',
      operation: 'search',
    },
    {
      method: 'GET',
      path: '/observations/:id',
      resourceType: 'Observation',
      permission: 'read_observation',
      description: 'Read observation',
      operation: 'read',
    },
    {
      method: 'POST',
      path: '/observations',
      resourceType: 'Observation',
      permission: 'write_observation',
      description: 'Create observation',
      operation: 'create',
    },
    {
      method: 'PUT',
      path: '/observations/:id',
      resourceType: 'Observation',
      permission: 'write_observation',
      description: 'Update observation',
      operation: 'update',
    },
  ],
}

/**
 * All endpoint groups in a stable iteration order.
 */
export const ALL_ENDPOINT_GROUPS: readonly EndpointGroup[] = [
  'patients',
  'encounters',
  'appointments',
  'notes',
  'claims',
  'consents',
  'observations',
] as const
