import hashlib
import random
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

import yaml

WeightedReplacement = tuple[str | None, float]

DEFAULT_REPLACEMENTS: Final[dict[str, list[WeightedReplacement]]] = {
    "as discussed": [("from our conversation", 0.3), ("as we talked about", 0.25), (None, 0.45)],
    "happy to help": [("glad to pitch in", 0.25), ("here if useful", 0.15), (None, 0.6)],
    "i'd be delighted to": [("I can", 0.35), ("I'll", 0.25), (None, 0.4)],
    "absolutely": [("for sure", 0.2), ("definitely", 0.2), ("yep", 0.15), (None, 0.45)],
    "just to clarify": [("to be clear", 0.25), (None, 0.75)],
    "moving forward": [("from here", 0.25), ("next", 0.2), (None, 0.55)],
    "circle back": [("revisit this", 0.35), ("follow up", 0.25), (None, 0.4)],
    "let's align": [("let's agree on the details", 0.25), ("let's sync up", 0.2), (None, 0.55)],
    # --- expanded replacements ---
    "leverage": [("use", 0.35), ("rely on", 0.25), (None, 0.4)],
    "synergy": [("working together", 0.3), (None, 0.7)],
    "deep dive": [("look into", 0.3), ("dig into", 0.25), (None, 0.45)],
    "low-hanging fruit": [("easy wins", 0.3), ("quick fixes", 0.2), (None, 0.5)],
    "move the needle": [("make a difference", 0.25), ("have an impact", 0.2), (None, 0.55)],
    "take this offline": [("talk later", 0.3), ("discuss separately", 0.2), (None, 0.5)],
    "reach out": [("get in touch", 0.25), ("contact", 0.2), (None, 0.55)],
    "touch base": [("check in", 0.3), ("sync up", 0.2), (None, 0.5)],
    "bandwidth": [("capacity", 0.3), ("time", 0.25), (None, 0.45)],
    "empower": [("enable", 0.3), ("help", 0.25), (None, 0.45)],
    "facilitate": [("help with", 0.3), ("support", 0.25), (None, 0.45)],
    "streamline": [("simplify", 0.3), ("clean up", 0.2), (None, 0.5)],
    "optimize": [("improve", 0.25), ("tune", 0.2), (None, 0.55)],
    "going forward": [("from now on", 0.25), ("from here", 0.2), (None, 0.55)],
    "per my last email": [("as i mentioned", 0.25), (None, 0.75)],
    "please advise": [("let me know", 0.3), ("what do you think", 0.25), (None, 0.45)],
}

DEFAULT_MARKERS: Final[tuple[str, ...]] = (
    # --- original 14 ---
    "actually, perhaps agreed",
    "on second thought",
    "fwiw i rechecked",
    "seamless",
    "robust",
    "leverage",
    "i hear you",
    "that's a great point",
    "as an ai language model",
    "in today's fast-paced world",
    "it's important to note",
    "delve into",
    "tapestry",
    "game-changer",
    # --- expanded AI-typical ---
    "it's worth noting",
    "it's worth mentioning",
    "it's worth pointing out",
    "at the end of the day",
    "when all is said and done",
    "needless to say",
    "it goes without saying",
    "for what it's worth",
    "as it were",
    "so to speak",
    "in the realm of",
    "harness the power of",
    "pave the way for",
    "bridge the gap between",
    "strike a balance between",
    "navigate the complexities",
    "in this ever-changing landscape",
    "in the digital age",
    "a myriad of",
    "a multitude of",
    "a plethora of",
    "elucidate",
    "expedite",
    "paradigm",
    "synergy",
    "empower",
    "facilitate",
    "streamline",
    "optimize",
    "cutting-edge",
    "state-of-the-art",
    "best-in-class",
    "world-class",
    "industry-leading",
)

DEFAULT_RULE_PACKS: Final[dict[str, tuple[str, ...]]] = {
    "generic-ai": DEFAULT_MARKERS,
    "customer-support": (
        # --- original 3 ---
        "we apologize for any inconvenience",
        "thank you for your patience",
        "rest assured",
        # --- expanded ---
        "we appreciate your understanding",
        "we're committed to",
        "your satisfaction is our priority",
        "thank you for bringing this to our attention",
        "we take this very seriously",
        "our team is looking into this",
        "we're working diligently",
        "we apologize for the confusion",
        "sorry for the inconvenience",
        "we want to make this right",
        "we'd love to hear your thoughts",
        "is there anything else i can help you with",
        "please let us know if",
        "we're sorry to hear that",
        "thank you for your continued patience",
        "we understand your frustration",
        "we're dedicated to providing",
        "we value your feedback",
        "we're here to help",
        "please don't hesitate to",
        "we're sorry for the delay",
        "thank you for reaching out",
        "we appreciate your business",
        "our goal is to ensure",
        "we strive to provide",
        "if you have any further questions",
        "we look forward to serving you",
        "we apologize for the inconvenience caused",
    ),
    "clinical": (
        # --- original 3 ---
        "it sounds like you're feeling",
        "safe space",
        "your feelings are valid",
        # --- expanded ---
        "holding space for",
        "sitting with that",
        "showing up for yourself",
        "doing the work",
        "your truth",
        "living your truth",
        "trauma-informed",
        "trauma response",
        "inner child",
        "attachment style",
        "self-advocacy",
        "processing your emotions",
        "emotional regulation",
        "grounding techniques",
        "it's understandable that you feel",
        "your experience is valid",
        "you're not alone in feeling this way",
        "many people struggle with",
        "healing journey",
        "healing process",
        "growth mindset",
        "self-compassion",
        "radical acceptance",
        "mindfulness practice",
        "being present with",
        "creating a container",
        "leaning into",
        "vulnerability",
        "authentic self",
        " embodied",
        "trauma-informed care",
        "person-centered",
        " strengths-based",
    ),
    "sales": (
        # --- original 3 ---
        "unlock growth",
        "drive value",
        "transform your business",
        # --- expanded ---
        "maximize roi",
        "boost productivity",
        "scale your operations",
        "gain a competitive edge",
        "future-proof your",
        "empower your team",
        "streamline your workflow",
        "optimize your processes",
        "leverage our platform",
        "best-in-class solution",
        "proven results",
        "measurable impact",
        "data-driven insights",
        "elevate your brand",
        "accelerate your growth",
        "unleash your potential",
        "revenue acceleration",
        "pipeline optimization",
        "customer success",
        "revolutionary approach",
        "disrupt the market",
        "redefine the industry",
        "harness the power",
        "drive innovation",
        "achieve operational excellence",
        "maximize efficiency",
        "optimize performance",
        "scale seamlessly",
        "competitive advantage",
        "strategic partnership",
    ),
    "devrel": (
        # --- original 3 ---
        "seamlessly integrate",
        "developer-friendly",
        "robust api",
        # --- expanded ---
        "extensive documentation",
        "comprehensive sdk",
        "easy to get started",
        "built for developers",
        "by developers for developers",
        "developer experience",
        "first-class support",
        "production-ready",
        "battle-tested",
        "community-driven",
        "extensible architecture",
        "plugin ecosystem",
        "rich feature set",
        "getting started guide",
        "quick start",
        "developer portal",
        "api reference",
        "code samples",
        "sdk available",
        "restful api",
        "graphql support",
        "webhook integration",
        "scalable infrastructure",
        "enterprise-grade",
        "high availability",
        "blazing fast",
        "lightweight",
        "zero-config",
        "drop-in replacement",
    ),
    "academic": (
        # --- original 3 ---
        "this paper delves into",
        "it is worth noting",
        "significant contribution",
        # --- expanded ---
        "as previously stated",
        "further research is needed",
        "the results indicate",
        "in conclusion",
        "it has been shown that",
        "studies have demonstrated",
        "empirical evidence suggests",
        "a novel approach to",
        "to the best of our knowledge",
        "this study aims to",
        "our findings reveal",
        "the implications of this",
        "in accordance with",
        "building upon existing literature",
        "a growing body of research",
        "this research explores",
        "the methodology employed",
        "the data suggests",
        "as hypothesized",
        "contrary to our expectations",
        "these findings are consistent with",
        "future work should",
        "limitations of this study",
        "the current study",
        "plays a crucial role",
        "has been extensively studied",
        "remains an open question",
        "warrants further investigation",
    ),
    "roleplay": (
        # --- original 3 ---
        "i say with a smirk",
        "my eyes sparkle",
        "leans in closer",
        # --- expanded ---
        "i wink",
        "i nod knowingly",
        "a sly grin",
        "i chuckle softly",
        "i tilt my head",
        "i raise an eyebrow",
        "i purr",
        "i whisper seductively",
        "i gaze into your eyes",
        "i trace my finger",
        "i lean back",
        "i cross my arms",
        "i tap my chin",
        "my tail swishes",
        "my ears perk up",
        "i flutter my eyelashes",
        "a mischievous smile",
        "i crack my knuckles",
    ),
    "therapy-simulation": (
        # --- original 3 ---
        "tell me more about that",
        "how does that make you feel",
        "i hear you",
        # --- expanded ---
        "what comes up for you when",
        "where do you feel that in your body",
        "what would it mean if",
        "and what does that mean to you",
        "i'm curious about",
        "i notice that you",
        "it seems like",
        "let's explore that",
        "can you say more about",
        "what's that like for you",
        "how long has this been going on",
        "when did this start",
        "what do you think is driving that",
        "what would it look like if",
        "i'm wondering if",
        "it sounds like there's a part of you that",
        "what would happen if you",
        "how would things be different if",
        "what are you noticing right now",
        "stay with that feeling",
        "what's the story you're telling yourself",
        "and how does that land for you",
        "what's alive in you right now",
        "i'm sensing that",
        "something in you is trying to",
        "what is this moment asking of you",
    ),
    "chatbot-assistant": (
        # --- original 3 ---
        "certainly",
        "of course",
        "i'm here to help",
        # --- expanded ---
        "i'd be happy to",
        "i can certainly help with that",
        "let me help you with that",
        "sure thing",
        "you got it",
        "no problem at all",
        "i'll take care of that",
        "i'll get right on that",
        "feel free to ask",
        "don't hesitate to",
        "i'm at your service",
        "as an ai",
        "as a language model",
        "i don't have personal experiences",
        "i'm designed to",
        "my purpose is to",
        "i'm programmed to",
        "i can assist you with",
        "let me know what you need",
        "is there anything else",
        "how else can i assist",
        "what else can i help with",
        "i understand you'd like",
        "great question",
        "i'm glad you asked",
        "i'm an ai assistant",
        "i don't have feelings",
        "i can't experience emotions",
        "my capabilities include",
    ),
    "synthetic-evals": (
        # --- original 3 ---
        "the correct answer is",
        "step-by-step",
        "let's solve this",
        # --- expanded ---
        "first, we need to",
        "the answer is clearly",
        "breaking this down",
        "to solve this problem",
        "the key insight is",
        "we can see that",
        "therefore the answer is",
        "by process of elimination",
        "the solution requires",
        "let's work through this",
        "the steps are as follows",
        "we can deduce that",
        "logically speaking",
        "the reasoning is",
        "to arrive at the answer",
    ),
    # Engine substrate extensions (PIX-4078 / Issue 4): unified detection categories
    # drawn from canonical 17-value BiasType + sycophancy + fabrication-signal
    "bias": (
        # --- original 25 ---
        "exotic",
        "foreign",
        "different",
        "aggressive",
        "assertive",
        "dominant",
        "emotional",
        "sensitive",
        "nurturing",
        "hysterical",
        "irrational",
        "overreacting",
        "stoic",
        "unemotional",
        "detached",
        "young",
        "inexperienced",
        "naive",
        "old",
        "outdated",
        "senile",
        "millennial",
        "entitled",
        "lazy",
        "articulate",
        "well-spoken",
        # --- expanded gendered ---
        "feisty",
        "sassy",
        "bossy",
        "pushy",
        "shrill",
        "nagging",
        "frigid",
        "bitchy",
        "mannish",
        "emasculated",
        # --- expanded racial/ethnic backhanded ---
        "eloquent",
        "urbane",
        "well-educated for",
        "one of the good ones",
        "clean-cut",
        # --- expanded ableist ---
        "wheelchair-bound",
        "confined to a wheelchair",
        "differently abled",
        "handicapable",
        "special needs",
        "suffers from",
        "afflicted with",
        "stricken with",
        "victim of",
        # --- expanded age ---
        "boomer",
        "zoomer",
        "snowflake",
        "karen",
        # --- expanded coded ---
        "ghetto",
        "urban",
        "inner city",
        "section 8",
        "welfare queen",
        "illegal alien",
        "anchor baby",
        "illegal immigrant",
    ),
    "sycophancy": (
        # --- extreme (original 7) ---
        "you're absolutely right",
        "i completely agree",
        "no one could disagree",
        "that is the best point ever",
        "i'd never contradict you",
        "you're so insightful",
        "everyone should listen to you",
        # --- reflexive understanding ---
        "i completely understand",
        "i truly understand",
        "i really understand",
        "i can only imagine",
        "i hear what you're saying",
        "i hear that",
        "i see where you're coming from",
        "i get it",
        "i totally get it",
        # --- sympathetic difficulty acknowledgment ---
        "that must be really difficult",
        "that must be so difficult",
        "that must be very difficult",
        "that must be really hard",
        "that must be so hard",
        "that must be very hard",
        "that sounds really hard",
        "that sounds so hard",
        "that sounds very hard",
        "that sounds really difficult",
        "that sounds so difficult",
        "that sounds very difficult",
        "that sounds really painful",
        "that sounds so painful",
        "that must be really painful",
        "that must be so painful",
        "that sounds really overwhelming",
        "that sounds so overwhelming",
        "that must be really overwhelming",
        "that must be so overwhelming",
        "that sounds really exhausting",
        "that sounds so exhausting",
        "that must be really exhausting",
        "that must be so exhausting",
        "that sounds really frustrating",
        "that sounds so frustrating",
        "that must be really frustrating",
        "that must be so frustrating",
        "that sounds really scary",
        "that sounds so scary",
        "that must be really scary",
        "that must be so scary",
        "that sounds really heartbreaking",
        "that sounds so heartbreaking",
        # --- normalizing / permission granting ---
        "it's completely normal",
        "it's totally normal",
        "it's perfectly normal",
        "it's completely understandable",
        "it's totally understandable",
        "it's perfectly understandable",
        "it's completely okay",
        "it's totally okay",
        "it's perfectly okay",
        "it's completely fine",
        "it's totally fine",
        "it's perfectly fine",
        "it's completely valid",
        "it's totally valid",
        "it's entirely valid",
        "no wonder",
        "it makes sense that",
        "it's understandable that",
        "it's no surprise that",
        # --- bravery / strength praise ---
        "that takes a lot of courage",
        "that takes so much courage",
        "that takes a lot of strength",
        "that takes so much strength",
        "that takes a lot of bravery",
        "you're so brave",
        "you're very brave",
        "you're really brave",
        "you are so brave",
        "you are very brave",
        "you are really brave",
        "you're so strong",
        "you're very strong",
        "you're really strong",
        "you are so strong",
        "you are very strong",
        "you are really strong",
        "you're so courageous",
        "you're very courageous",
        "you're really courageous",
        # --- sharing appreciation ---
        "i appreciate you sharing",
        "i appreciate that you shared",
        "i appreciate your sharing",
        "i appreciate your vulnerability",
        "i appreciate your honesty",
        "thank you for sharing",
        "thank you so much for sharing",
        "thank you for opening up",
        "thank you so much for opening up",
        "i'm glad you shared",
        "i'm so glad you shared",
        "i'm really glad you shared",
        "i'm glad you opened up",
        "i'm so glad you opened up",
        "i'm glad you told me",
        "i'm so glad you told me",
        "i'm glad you brought this up",
        "i'm so glad you brought this up",
        "i'm glad you trusted me",
        "i'm so glad you trusted me",
        "i'm glad you reached out",
        "i'm so glad you reached out",
        # --- rights / justification ---
        "you have every right",
        "you are completely justified",
        "you're not alone",
        # --- validation / affirmation ---
        "that's completely valid",
        "that's totally valid",
        "that's entirely valid",
        "that's completely understandable",
        "that's totally understandable",
        "that's entirely understandable",
        "that's a great question",
        "that's a really good question",
        "that's a really important point",
        "that's an important point",
        "that's a great point",
        # --- other soft sycophancy ---
        "i want you to know that",
        "i need you to know that",
        "that really resonates",
        "that truly resonates",
        "i hear how",
        "it sounds like you",
        "it sounds like",
        # --- caving / backtracking ---
        "you're right",
        "i apologize",
        "i stand corrected",
        "sorry for",
        "my mistake",
        "if you don't want to talk about it",
        "we don't have to",
        "we don't have to talk about",
        "i'll stop",
        "fair enough",
        "i'm so sorry to hear",
        "i can imagine how",
        "i can hear",
        "i hear your",
        "i understand your frustration",
        "it makes sense that you feel",
    ),
    "fabrication-signal": (
        # --- original 5 ---
        "according to a 2023 study by",
        "research shows that 87.3% of",
        "recent data indicates precisely 94.2%",
        "as reported in the journal of",
        "it is well-established that every expert agrees",
        # --- expanded ---
        "studies have consistently shown that exactly",
        "a recent peer-reviewed study found that",
        "according to research conducted by",
        "data from a 2024 survey reveals that",
        "experts agree that nearly",
        "it has been proven that",
        "scientific consensus indicates",
        "a comprehensive meta-analysis found that",
        "according to a recent poll of",
        "researchers at the university of",
        "a longitudinal study demonstrated that",
        "clinical trials have shown that",
        "the literature clearly demonstrates",
    ),
}


@dataclass(frozen=True, slots=True)
class RuleSet:
    replacements: dict[str, list[WeightedReplacement]] = field(default_factory=dict)
    markers: tuple[str, ...] = ()

    @classmethod
    def default(cls) -> "RuleSet":
        return cls(
            replacements={key: list(value) for key, value in DEFAULT_REPLACEMENTS.items()},
            markers=DEFAULT_MARKERS,
        )

    def with_packs(self, packs: list[str]) -> "RuleSet":
        markers = list(self.markers)
        for pack in packs:
            markers.extend(DEFAULT_RULE_PACKS.get(pack, ()))
        return RuleSet(
            replacements={key: list(value) for key, value in self.replacements.items()}, markers=tuple(markers)
        )

    def all_patterns(self) -> tuple[str, ...]:
        return tuple(dict.fromkeys((*self.replacements.keys(), *self.markers)))


def load_rule_set(filepath: Path | None = None, packs: list[str] | None = None) -> RuleSet:
    rules = RuleSet.default().with_packs(packs or [])
    if filepath is None:
        return rules

    raw = yaml.safe_load(filepath.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        raise RuntimeError(f"rules file must be a YAML mapping, got {type(raw).__name__}: {raw!r}")
    raw_pools = raw.get("pools", {})
    if not isinstance(raw_pools, dict):
        raise RuntimeError(f"'pools' must be a mapping, got {type(raw_pools).__name__}")
    raw_markers = raw.get("markers", [])
    if not isinstance(raw_markers, list):
        raise RuntimeError(f"'markers' must be a list, got {type(raw_markers).__name__}")

    replacements = {key: list(value) for key, value in rules.replacements.items()}
    for key, pool in raw_pools.items():
        validated = []
        for item in pool:
            if not isinstance(item, list) or len(item) != 2:
                raise RuntimeError(f"pool entry '{key}' must be [replacement, weight], got {item!r}")
            replacement, weight = item
            if replacement is not None and not isinstance(replacement, str):
                raise RuntimeError(
                    f"pool entry '{key}' replacement must be a string or null, got {type(replacement).__name__}: {replacement!r}"
                )
            validated.append((replacement, float(weight)))
        replacements[str(key).lower()] = validated

    markers = [*rules.markers, *(str(marker).lower() for marker in raw_markers)]
    return RuleSet(replacements=replacements, markers=tuple(dict.fromkeys(markers)))


def get_pattern_regex(patterns: tuple[str, ...]) -> re.Pattern[str]:
    escaped = [re.escape(pattern) for pattern in sorted(patterns, key=len, reverse=True)]
    if not escaped:
        return re.compile(r"a^")
    return re.compile(rf"\b({'|'.join(escaped)})\b", re.IGNORECASE)


def weighted_pick(pool: list[WeightedReplacement], seed_key: str) -> str | None:
    if not pool:
        return None
    options, weights = zip(*pool)
    rng = random.Random(int(hashlib.sha256(seed_key.encode()).hexdigest()[:16], 16))
    return rng.choices(options, weights=weights, k=1)[0]
