# coding: utf-8

# flake8: noqa
"""
    Pixelated Empathy API

    The Pixelated Empathy API provides programmatic access to the platform's core features, including user profiles, mental health analytics, bias detection, and memory management.  ### Authentication (Dual Mode)  Most endpoints require authentication using either a **JWT (Bearer Token)** or an **API Key**. - For browser-based applications, use the JWT provided by Auth0. - For server-side integrations, use an API Key in the `X-API-Key` header.  Three authentication strategies are available: | Strategy | Use Case | Header | |---|---|---| | `jwtOnly` | Browser sessions, user-facing requests | `Authorization: Bearer <token>` | | `apiKeyOnly` | Server-to-server, background jobs | `X-API-Key: <key>` | | `either` | Any authenticated caller | Both accepted |  ### Scope-Based Access Control  API keys are bound to **scopes** that control which endpoints they can access:  | Scope | Access | |---|---| | `read` | GET on API resources | | `write` | POST, PUT, PATCH on API resources | | `admin` | Administrative endpoints | | `memory:read` | Memory read operations | | `memory:write` | Memory write operations | | `developer:manage` | API key management | | `analytics:read` | Analytics and reporting |  Routes are organised into **families** that define default authentication and scope behaviour: `public`, `user`, `developer`, `admin`, `system`. 

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@pixelatedempathy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from pixelated_empathy_sdk.models.admin_user_view import AdminUserView
from pixelated_empathy_sdk.models.api_key import ApiKey
from pixelated_empathy_sdk.models.auth_callback200_response import AuthCallback200Response
from pixelated_empathy_sdk.models.auth_logout200_response import AuthLogout200Response
from pixelated_empathy_sdk.models.auth_me200_response import AuthMe200Response
from pixelated_empathy_sdk.models.auth_me200_response_user import AuthMe200ResponseUser
from pixelated_empathy_sdk.models.auth_refresh200_response import AuthRefresh200Response
from pixelated_empathy_sdk.models.auth_refresh_request import AuthRefreshRequest
from pixelated_empathy_sdk.models.bias_analysis_request import BiasAnalysisRequest
from pixelated_empathy_sdk.models.bias_analysis_result import BiasAnalysisResult
from pixelated_empathy_sdk.models.bias_analysis_result_biases_inner import BiasAnalysisResultBiasesInner
from pixelated_empathy_sdk.models.client_profile import ClientProfile
from pixelated_empathy_sdk.models.create_api_key_request import CreateApiKeyRequest
from pixelated_empathy_sdk.models.create_api_key_response import CreateApiKeyResponse
from pixelated_empathy_sdk.models.create_memory201_response import CreateMemory201Response
from pixelated_empathy_sdk.models.create_memory_request import CreateMemoryRequest
from pixelated_empathy_sdk.models.create_training_session201_response import CreateTrainingSession201Response
from pixelated_empathy_sdk.models.create_training_session_request import CreateTrainingSessionRequest
from pixelated_empathy_sdk.models.error import Error
from pixelated_empathy_sdk.models.fine_tuning_job import FineTuningJob
from pixelated_empathy_sdk.models.get_memory200_response import GetMemory200Response
from pixelated_empathy_sdk.models.get_memory_stats200_response import GetMemoryStats200Response
from pixelated_empathy_sdk.models.get_memory_stats200_response_stats import GetMemoryStats200ResponseStats
from pixelated_empathy_sdk.models.get_preferences200_response import GetPreferences200Response
from pixelated_empathy_sdk.models.get_profile200_response import GetProfile200Response
from pixelated_empathy_sdk.models.health_status import HealthStatus
from pixelated_empathy_sdk.models.list_api_keys200_response import ListApiKeys200Response
from pixelated_empathy_sdk.models.list_memories200_response import ListMemories200Response
from pixelated_empathy_sdk.models.list_memories200_response_pagination import ListMemories200ResponsePagination
from pixelated_empathy_sdk.models.list_training_jobs200_response import ListTrainingJobs200Response
from pixelated_empathy_sdk.models.list_training_sessions200_response import ListTrainingSessions200Response
from pixelated_empathy_sdk.models.list_users200_response import ListUsers200Response
from pixelated_empathy_sdk.models.memory_session import MemorySession
from pixelated_empathy_sdk.models.memory_turn import MemoryTurn
from pixelated_empathy_sdk.models.memory_turn_create import MemoryTurnCreate
from pixelated_empathy_sdk.models.pagination import Pagination
from pixelated_empathy_sdk.models.product_memory_record import ProductMemoryRecord
from pixelated_empathy_sdk.models.rotate_api_key200_response import RotateApiKey200Response
from pixelated_empathy_sdk.models.rotate_api_key200_response_key import RotateApiKey200ResponseKey
from pixelated_empathy_sdk.models.search_content200_response import SearchContent200Response
from pixelated_empathy_sdk.models.search_memories_get200_response import SearchMemoriesGet200Response
from pixelated_empathy_sdk.models.search_memories_get200_response_pagination import SearchMemoriesGet200ResponsePagination
from pixelated_empathy_sdk.models.search_memories_get200_response_user import SearchMemoriesGet200ResponseUser
from pixelated_empathy_sdk.models.search_memories_post_request import SearchMemoriesPostRequest
from pixelated_empathy_sdk.models.search_result import SearchResult
from pixelated_empathy_sdk.models.submit_training_job201_response import SubmitTrainingJob201Response
from pixelated_empathy_sdk.models.submit_training_job_request import SubmitTrainingJobRequest
from pixelated_empathy_sdk.models.training_session import TrainingSession
from pixelated_empathy_sdk.models.user_preferences import UserPreferences
from pixelated_empathy_sdk.models.user_preferences_notifications import UserPreferencesNotifications
from pixelated_empathy_sdk.models.user_preferences_update import UserPreferencesUpdate
from pixelated_empathy_sdk.models.user_profile import UserProfile
from pixelated_empathy_sdk.models.user_profile_update import UserProfileUpdate
from pixelated_empathy_sdk.models.v1_create_memory_request import V1CreateMemoryRequest
from pixelated_empathy_sdk.models.v1_create_memory_response import V1CreateMemoryResponse
from pixelated_empathy_sdk.models.v1_delete_memory_response import V1DeleteMemoryResponse
from pixelated_empathy_sdk.models.v1_delete_memory_response_data import V1DeleteMemoryResponseData
from pixelated_empathy_sdk.models.v1_error import V1Error
from pixelated_empathy_sdk.models.v1_get_memory_response import V1GetMemoryResponse
from pixelated_empathy_sdk.models.v1_list_memories_response import V1ListMemoriesResponse
from pixelated_empathy_sdk.models.v1_memory_scope import V1MemoryScope
from pixelated_empathy_sdk.models.v1_pagination import V1Pagination
from pixelated_empathy_sdk.models.v1_public_memory import V1PublicMemory
from pixelated_empathy_sdk.models.v1_retention_policy import V1RetentionPolicy
from pixelated_empathy_sdk.models.v1_search_memories_response import V1SearchMemoriesResponse
from pixelated_empathy_sdk.models.v1_search_memory_request import V1SearchMemoryRequest
from pixelated_empathy_sdk.models.v1_update_memory_request import V1UpdateMemoryRequest
from pixelated_empathy_sdk.models.v1_update_memory_response import V1UpdateMemoryResponse
from pixelated_empathy_sdk.models.version_info import VersionInfo
