# coding: utf-8

"""
    Pixelated Memory API (v1)

    Public v1 memory API contract. Schemas derive from `src/lib/memory/contract/v1.ts`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PublicMemory(BaseModel):
    """
    PublicMemory
    """ # noqa: E501
    id: Optional[StrictStr] = None
    content: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    retention: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    version: Optional[StrictInt] = None
    importance: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "content", "scope", "retention", "category", "tags", "version", "importance", "createdAt", "updatedAt"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['session', 'arc', 'trait', 'fact']):
            raise ValueError("must be one of enum values ('session', 'arc', 'trait', 'fact')")
        return value

    @field_validator('retention')
    def retention_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ephemeral', 'short_term', 'long_term', 'permanent']):
            raise ValueError("must be one of enum values ('ephemeral', 'short_term', 'long_term', 'permanent')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicMemory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicMemory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "content": obj.get("content"),
            "scope": obj.get("scope"),
            "retention": obj.get("retention"),
            "category": obj.get("category"),
            "tags": obj.get("tags"),
            "version": obj.get("version"),
            "importance": obj.get("importance"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


